"use client";

import { useMemo, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Clock3, Heart, Printer, Search, Sparkles, X } from "lucide-react";
import "./recipes.css";

type Recipe = {
  id: string;
  title: string;
  subtitle: string;
  image: string;
  description: string;
  prep: string;
  cook: string;
  total: string;
  yield: string;
  tags: string[];
  color: string;
  ingredients: { category: string; items: string[] }[];
  steps: { title: string; text: string }[];
  note: string;
};

const recipes: Recipe[] = [
  { id: "lauras-cookies", title: "Laura's Cookies", subtitle: "Copycat · tonight version", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuPL2oUUxSRJR19t6-7fd1wDT-tyJ4d8k3OWH0OXgOJNLzGw-x7XjFCpcl&s=10", description: "Soft sugar cookies with no overnight wait. A short freezer chill gets you from craving to frosted cookie tonight.", prep: "15 min", cook: "10 min", total: "2 hr 20 min", yield: "24–30", tags: ["Sweet", "Baking", "Weekend"], color: "lilac", ingredients: [{ category: "The dough", items: ["5 cups all-purpose flour", "1½ cups granulated sugar", "1 cup unsalted butter, softened", "1 cup full-fat sour cream", "2 large eggs", "2 tsp baking powder", "2 tsp vanilla + ½ tsp salt"] }, { category: "Quick icing", items: ["3 cups powdered sugar", "4 tbsp softened butter", "3–4 tbsp milk", "Vanilla and a pinch of salt"] }], steps: [{ title: "Make the dough", text: "Cream butter and sugar until fluffy. Beat in sour cream, eggs, and vanilla. Fold in the dry ingredients just until a soft dough forms." }, { title: "Freeze, don’t wait", text: "Divide dough into two disks, wrap, and freeze for 45 minutes. It should be firm enough to roll, not solid." }, { title: "Roll and cut", text: "Heat oven to 350°F. Roll to ¼ inch on a lightly floured surface and cut your favorite shapes." }, { title: "Bake and cool", text: "Bake 8–10 minutes, before the edges brown. Cool on the pan 5 minutes, then move to a rack." }, { title: "Frost generously", text: "Whisk icing smooth. Frost fully cooled cookies, then eat one standing at the counter." }], note: "The freezer is the secret: it gives the flour time to hydrate just enough without turning this into a tomorrow project." },
  { id: "apple-chicken-chili", title: "White Cheddar", subtitle: "Apple chicken chili", image: "https://www.littlebroken.com/wp-content/uploads/2023/09/Apple-Chicken-Chili-18.jpg", description: "Savory, cheesy chicken chili with a quiet apple note in the background—not a single awkward fruit chunk.", prep: "20 min", cook: "40 min", total: "1 hour", yield: "6 bowls", tags: ["Dinner", "Cozy", "One pot"], color: "mint", ingredients: [{ category: "Chili", items: ["1 lb ground chicken", "1 yellow onion, diced", "3 cloves garlic, minced", "4 cups chicken broth", "2 cans cannellini beans, drained", "1 can diced green chiles", "1 cup whole milk"] }, { category: "The flavor", items: ["1 apple, finely grated", "2 cups sharp white cheddar", "Cumin, chili powder, oregano", "Salt, pepper, and a little honey"] }], steps: [{ title: "Build the base", text: "Sauté onion in a Dutch oven until soft. Add garlic for 30 seconds, then brown the chicken with the spices." }, { title: "Simmer", text: "Add broth, grated apple, chiles, and beans. Simmer gently for 20 minutes to let the apple disappear into the broth." }, { title: "Make it creamy", text: "Stir in milk and cheese over low heat. Do not boil once the dairy is in." }, { title: "Rest and serve", text: "Let stand 5 minutes, then taste for salt and finish with cilantro or crushed tortilla chips." }], note: "Grating the apple gives the chili its subtle sweetness while keeping every spoonful completely savory." },
  { id: "skyline-chili", title: "Copycat Skyline", subtitle: "Cincinnati chili", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWgr9EfmL8CBqEt4RRxbgdFZJO4yBG1pKAhJ-TsdB0LtWJgdsfTAq-MLU&s=10", description: "The spiced, silky meat sauce that belongs on spaghetti, hot dogs, and exactly as much cheese as you can manage.", prep: "5 min", cook: "1 hr 30", total: "1 hr 35", yield: "6 servings", tags: ["Dinner", "Ohio", "Big batch"], color: "gold", ingredients: [{ category: "Sauce", items: ["1½ lb ground beef", "4 cups beef broth", "1 can tomato sauce", "1 onion, minced", "2 tbsp chili powder", "Cinnamon, allspice, cloves", "Cocoa powder, Worcestershire, bay leaf"] }, { category: "For serving", items: ["Spaghetti or hot dogs", "Finely shredded cheddar", "Diced onion and beans"] }], steps: [{ title: "Start it silky", text: "Add raw beef to cool broth and break it up completely with your fingers or a potato masher." }, { title: "Season everything", text: "Stir in tomato sauce, onion, spices, cocoa, Worcestershire, and bay leaf." }, { title: "Boil, then barely simmer", text: "Bring to a boil, then lower to a lazy simmer for 75 minutes, stirring occasionally." }, { title: "Serve your way", text: "Fish out the bay leaf. Spoon over spaghetti or dogs and build your preferred ‘way’ with cheese, onion, and beans." }], note: "The unusual step of starting with cool broth is what creates that fine, signature chili texture." },
  { id: "best-classic-chili", title: "The Best", subtitle: "Classic chili", image: "https://www.thewholesomedish.com/wp-content/uploads/2018/05/The-Best-Classic-Chili-550.jpg", description: "No surprises, just a genuinely excellent bowl of classic beef-and-bean chili.", prep: "5 min", cook: "25 min", total: "30 min", yield: "6 servings", tags: ["Dinner", "Quick", "Classic"], color: "coral", ingredients: [{ category: "Pot essentials", items: ["1 lb ground beef", "1 onion, diced", "2 cloves garlic", "1 can diced tomatoes", "1 can tomato sauce", "2 cans kidney beans", "Chili powder, cumin, paprika"] }], steps: [{ title: "Sauté and brown", text: "Cook onion until soft, then add beef and brown well. Drain excess fat if needed." }, { title: "Season it", text: "Add garlic and spices. Stir for a minute until fragrant." }, { title: "Add the good stuff", text: "Pour in tomatoes, sauce, and beans. Bring to a steady simmer." }, { title: "Let it settle", text: "Simmer uncovered 20 minutes. Rest for 5 before serving with your favorite toppings." }], note: "A short rest is the difference between chili that tastes fine and chili that tastes finished." },
  { id: "sams-fried-chicken", title: "Sam's Fried", subtitle: "Chicken", image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=1200&q=85", description: "Extra-crispy buttermilk fried chicken with a boldly seasoned crust.", prep: "15 min", cook: "15 min", total: "1 hr 30", yield: "2 breasts", tags: ["Dinner", "Crispy", "Weekend"], color: "blue", ingredients: [{ category: "Chicken", items: ["2 chicken breasts, halved", "1 cup buttermilk", "1½ cups flour", "Paprika, garlic powder, cayenne", "Salt and lots of black pepper", "Neutral oil for frying"] }], steps: [{ title: "Marinate", text: "Season chicken and cover in buttermilk. Refrigerate for at least one hour." }, { title: "Make the dredge", text: "Mix flour with the spices. Keep a small bowl of buttermilk nearby for extra craggy bits." }, { title: "Heat and coat", text: "Heat ¾ inch oil to 350°F. Dredge chicken, dip in buttermilk, then dredge again." }, { title: "Fry", text: "Fry 6–8 minutes per side until deeply golden and the center reaches 165°F. Drain on a rack, not paper towels." }], note: "Season the flour assertively—some of that flavor stays in the oil, and the crust needs to carry the chicken." },
  { id: "chuck-roast", title: "Benny's", subtitle: "Chuck roast", image: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/tk%2Fphoto%2F2025%2F10-2025%2F2025-10-pot-roast%2Fpot-roast-663", description: "A tender slow-cooker roast with vegetables and a savory gravy that makes itself.", prep: "20 min", cook: "8 hours", total: "8 hr 20", yield: "4–6", tags: ["Dinner", "Slow cooker", "Sunday"], color: "rust", ingredients: [{ category: "Crockpot", items: ["3–4 lb chuck roast", "Potatoes, carrots, and onion", "Beef broth", "Ranch seasoning + onion soup mix", "Butter and pepperoncini peppers", "Cornstarch for gravy"] }], steps: [{ title: "Sear the roast", text: "Salt and pepper the roast, then sear in a hot skillet for a deeply browned crust." }, { title: "Layer the pot", text: "Place vegetables in the crockpot, set the roast on top, and add broth, seasonings, butter, and peppers." }, { title: "Cook low and slow", text: "Cover and cook on low for 8 hours, until the roast pulls apart without resistance." }, { title: "Make gravy", text: "Whisk cornstarch slurry into the cooking liquid and cook until glossy. Serve over everything." }], note: "Searing takes ten extra minutes, but it gives the broth a roasted, not merely salty, flavor." },
  { id: "cinnabon-rolls", title: "Cinnabon Rolls", subtitle: "But better", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQn3hHwscTvL8UlcTDmDTl5Hz9cxS7ANSlXs04AI9ygXPBEe-PUQJ6GNow&s=10", description: "Pillowy cinnamon rolls with a rich cream-cheese glaze. Mall energy, better morning.", prep: "3 hr 30", cook: "20 min", total: "4 hours", yield: "12 rolls", tags: ["Sweet", "Baking", "Brunch"], color: "pink", ingredients: [{ category: "Dough & filling", items: ["Warm milk, yeast, sugar, eggs", "Flour, butter, and salt", "Brown sugar and cinnamon", "Heavy cream for the pan"] }, { category: "Glaze", items: ["Cream cheese", "Butter", "Powdered sugar", "Vanilla + a splash of milk"] }], steps: [{ title: "Make a soft dough", text: "Bloom yeast in warm milk, then mix in the remaining dough ingredients until smooth and elastic." }, { title: "First rise", text: "Cover and let rise until doubled, about 90 minutes." }, { title: "Roll, fill, and cut", text: "Roll into a rectangle, spread butter, cover with cinnamon sugar, then roll tightly and slice into 12." }, { title: "Rise and bake", text: "Let rise in the pan until puffy. Pour a little cream around the rolls and bake at 375°F until lightly golden." }, { title: "Glaze while warm", text: "Beat the glaze smooth and spread over warm—not scorching—rolls." }], note: "The cream around the rolls is not optional. It keeps the centers impossibly soft." },
  { id: "ny-style-pizza", title: "Authentic NY", subtitle: "Style pizza", image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRV7FE0GJzoL364jS-cZaYKX5qMM0L6iHQcnDzJ7Fq9A&s=10", description: "A foldable, chewy New York slice with a crisp underside and a proper long fermentation.", prep: "30 min", cook: "5 min", total: "3 days", yield: "2 pizzas", tags: ["Dinner", "Baking", "Project"], color: "tomato", ingredients: [{ category: "Dough", items: ["Bread flour", "Cold water", "Salt, yeast, and a touch of sugar", "Olive oil" ] }, { category: "Top it", items: ["Crushed tomatoes", "Low-moisture mozzarella", "Dried oregano", "Semolina or flour for launching"] }], steps: [{ title: "Mix and knead", text: "Mix flour and water, rest 20 minutes, then add yeast and salt. Knead until smooth." }, { title: "Cold ferment", text: "Divide into two balls and refrigerate in covered containers for 2–3 days." }, { title: "Heat everything", text: "Preheat your stone or steel at your oven’s highest setting for at least 45 minutes." }, { title: "Shape and bake", text: "Stretch gently, top sparingly, and bake until the cheese blisters and crust is spotted." }, { title: "The slice trick", text: "Cool a few minutes, then reheat slices directly on the rack for a crisp, foldable bottom." }], note: "Give the dough time. That cold fermentation is where the chew and flavor actually happen." },
  { id: "golden-milk-banana-smoothie", title: "Golden Milk", subtitle: "Banana smoothie", image: "https://images.unsplash.com/photo-1553530666-ba11a90a0868?auto=format&fit=crop&w=1200&q=85", description: "A creamy, warmly spiced turmeric smoothie for one large serving.", prep: "5 min", cook: "0 min", total: "5 min", yield: "1 large", tags: ["Drink", "Quick", "Cozy"], color: "gold", ingredients: [{ category: "Blend this", items: ["1 ripe banana, preferably frozen", "1 cup milk of choice", "½ tsp ground turmeric", "¼ tsp ground cinnamon", "Small pinch of ground ginger", "Tiny pinch of black pepper", "1 tsp honey or maple syrup, optional", "½ tsp vanilla, optional", "A few ice cubes if your banana isn’t frozen"] }], steps: [{ title: "Add everything", text: "Add all ingredients to a blender." }, { title: "Blend until creamy", text: "Blend until smooth and creamy, with no banana pieces left behind." }, { title: "Taste and adjust", text: "Add a little more honey or maple syrup if you want it sweeter, then blend once more." }], note: "The tiny pinch of black pepper pairs well with turmeric, but keep it very small so you don’t taste it. For an extra-creamy smoothie, add 1–2 tablespoons of Greek yogurt or nut butter." },
  { id: "buckeye-candy", title: "Buckeye", subtitle: "Candy · no wax", image: "https://www.nutmegnanny.com/wp-content/uploads/2020/12/peanut-butter-buckeyes-7.jpg", description: "Creamy peanut butter centers dipped in chocolate, with no paraffin wax needed.", prep: "20 min", cook: "5 min", total: "55 min", yield: "About 36", tags: ["Sweet", "Baking", "No bake"], color: "lilac", ingredients: [{ category: "Peanut butter centers", items: ["1½ cups creamy peanut butter", "½ cup butter, softened", "1 tsp vanilla", "3½–4 cups powdered sugar"] }, { category: "Chocolate coating", items: ["2 cups chocolate chips", "1 tbsp coconut oil or shortening, optional"] }], steps: [{ title: "Make the filling", text: "Mix peanut butter, butter, and vanilla until smooth." }, { title: "Add the sugar", text: "Stir in powdered sugar a little at a time until the dough is firm enough to roll." }, { title: "Roll and chill", text: "Roll into 1-inch balls, place on a parchment-lined tray, and chill for about 30 minutes." }, { title: "Melt the chocolate", text: "Melt chocolate chips with coconut oil or shortening, if using, until smooth." }, { title: "Dip each buckeye", text: "Stick a toothpick into each peanut butter ball and dip it into chocolate, leaving a small circle of peanut butter showing on top." }, { title: "Set", text: "Place back on parchment and let the chocolate set." }], note: "Keep them in the fridge so they stay firm. You do not need paraffin wax—the chocolate will set just fine on its own." },
  { id: "chai-latte", title: "Benny's", subtitle: "Chai latte", image: "https://images.unsplash.com/photo-1577968897966-3d4325b36b61?auto=format&fit=crop&w=1200&q=85", description: "A quick stovetop chai that hits the exact warm, sweet, spicy note.", prep: "2 min", cook: "5 min", total: "7 min", yield: "1 mug", tags: ["Drink", "Quick", "Cozy"], color: "lavender", ingredients: [{ category: "One mug", items: ["½ cup water", "2 chai tea bags", "½ cup milk", "1–2 tsp brown sugar or honey", "Cinnamon, optional"] }], steps: [{ title: "Brew it strong", text: "Bring water to a boil, add tea bags, and steep for 3–4 minutes." }, { title: "Add milk and sweetness", text: "Stir in milk and sweetener; warm just until steaming." }, { title: "Strain and settle in", text: "Remove tea bags, pour into your favorite mug, and add cinnamon if you want it." }], note: "For an iced version, brew the tea extra strong, cool it, then pour over ice with cold milk." },
  { id: "honey-garlic-salmon", title: "Honey Garlic", subtitle: "Glazed salmon", image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?auto=format&fit=crop&w=1200&q=85", description: "Sticky, sweet, garlicky salmon in one pan and under 20 minutes.", prep: "8 min", cook: "10 min", total: "18 min", yield: "4 servings", tags: ["Dinner", "Quick", "One pan"], color: "orange", ingredients: [{ category: "Salmon & glaze", items: ["4 salmon fillets", "Honey", "Soy sauce", "4 cloves garlic, minced", "Lemon juice", "Butter and black pepper"] }], steps: [{ title: "Make the glaze", text: "Whisk honey, soy sauce, garlic, lemon, and pepper in a small bowl." }, { title: "Sear the salmon", text: "Cook salmon in a hot oven-safe skillet, skin-side down if it has skin, until nearly cooked through." }, { title: "Glaze and broil", text: "Add butter and glaze, spoon over the fish, then broil briefly until bubbling and lacquered." }, { title: "Serve right away", text: "Finish with lemon and serve with rice or greens while the glaze is glossy." }], note: "Keep an eye on the broiler—the honey goes from caramelized to burned in a blink." },
  { id: "garlic-chicken-gyros", title: "Garlic Chicken", subtitle: "Gyros with fries", image: "https://www.recipetineats.com/tachyon/2015/06/Greek-Chicken-Gyros_original-pics__8.jpg", description: "Street-food-style gyros stuffed with garlicky chicken, fresh vegetables, and crispy fries.", prep: "45 min", cook: "15 min", total: "1 hour", yield: "4 gyros", tags: ["Dinner", "Fun", "Chicken"], color: "green", ingredients: [{ category: "The gyro", items: ["Chicken thighs", "Greek yogurt, lemon, garlic, oregano", "Pita bread", "French fries", "Tomato, red onion, feta"] }, { category: "Garlic sauce", items: ["Greek yogurt or mayo", "Garlic", "Lemon juice", "Salt and pepper"] }], steps: [{ title: "Marinate the chicken", text: "Toss chicken with yogurt, lemon, garlic, and oregano. Let sit at least 30 minutes." }, { title: "Make the sauce", text: "Stir sauce ingredients together and refrigerate while you cook." }, { title: "Cook fries and chicken", text: "Bake or air-fry the fries. Sear chicken until browned and cooked through, then slice." }, { title: "Build each gyro", text: "Warm pita, spread on sauce, and pile on chicken, fries, vegetables, feta, and another drizzle of sauce." }], note: "Toss hot fries with oregano, garlic powder, and lemon zest before assembling. They taste like they belong there." },
  { id: "tuna-salad", title: "Tuna Salad", subtitle: "The savory one", image: "https://muybuenoblog.com/wp-content/uploads/2024/05/Tuna-Salad-with-Chopped-EggsTuna-Salad-with-Chopped-Eggs.jpeg", description: "Creamy, savory tuna salad with hard-boiled eggs and just enough Worcestershire to make it special.", prep: "10 min", cook: "0 min", total: "10 min", yield: "2–3 servings", tags: ["Lunch", "Quick", "Classic"], color: "blue", ingredients: [{ category: "Mix it up", items: ["1 can tuna, drained", "2 hard-boiled eggs, chopped", "2–3 tbsp mayonnaise", "1 tsp Worcestershire sauce", "1 tsp mustard", "1–2 tbsp finely diced onion or green onion", "Salt and black pepper"] }, { category: "Optional extras", items: ["A little pickle relish", "Paprika", "A squeeze of lemon"] }], steps: [{ title: "Get everything ready", text: "Drain the tuna well, chop the eggs, and finely dice the onion or green onion." }, { title: "Mix until creamy", text: "Combine tuna, eggs, mayonnaise, Worcestershire, mustard, onion, salt, and pepper in a bowl." }, { title: "Taste and tune", text: "Add another small splash of Worcestershire if you want a more savory flavor. Fold in relish, paprika, or lemon if using." }, { title: "Serve your way", text: "Pile it on toast, crackers, lettuce wraps, or between two slices of bread." }], note: "Start with two tablespoons of mayonnaise, then add the third only if you want it extra creamy." },
  { id: "gingerbread-cookies", title: "Gingerbread", subtitle: "Cookies", image: "https://www.lovefromtheoven.com/wp-content/uploads/2018/09/ginger-cookies-5-of-5.jpg", description: "Soft-centered, crisp-edged gingerbread cookies with lots of molasses and a confident amount of spice.", prep: "4 hours", cook: "10 min", total: "4 hr 30", yield: "24 cookies", tags: ["Sweet", "Baking", "Holiday"], color: "rust", ingredients: [{ category: "Dry ingredients", items: ["3½ cups all-purpose flour", "1 tsp baking soda + ½ tsp salt", "1 tbsp ground ginger", "1 tbsp ground cinnamon", "½ tsp each allspice and cloves"] }, { category: "Wet ingredients", items: ["10 tbsp unsalted butter, softened", "¾ cup packed brown sugar", "⅔ cup unsulphured or dark molasses", "1 large egg", "1 tsp vanilla extract"] }, { category: "To finish", items: ["Flour for rolling", "Cookie icing, royal icing, or buttercream"] }], steps: [{ title: "Whisk the dry ingredients", text: "Whisk flour, baking soda, salt, ginger, cinnamon, allspice, and cloves together in a medium bowl." }, { title: "Make the dough", text: "Beat butter until creamy, then beat in brown sugar and molasses. Add egg and vanilla, then mix in the dry ingredients on low until a thick, slightly sticky dough forms." }, { title: "Chill two discs", text: "Divide dough in half, wrap each portion, and pat into a disc. Chill for at least 3 hours and up to 3 days." }, { title: "Roll and cut", text: "Heat oven to 350°F. Roll one chilled disc to ¼-inch thick on a generously floured surface, cut shapes, and place them 1 inch apart on lined baking sheets." }, { title: "Bake and cool", text: "Bake 9–10 minutes (adjust for cutter size). Cool on the sheet for 5 minutes, then move to a rack to cool completely." }, { title: "Decorate", text: "Ice only after the cookies are fully cool. Add the smiles, bow-ties, and buttons." }], note: "The long chill is what keeps the shapes tidy. If the dough gets sticky while rolling, flour the surface and return it to the fridge for a few minutes." },
  { id: "chicken-fried-rice", title: "Chicken", subtitle: "Fried rice", image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1200&q=85", description: "Fast, takeout-style fried rice made for that container of cold rice in the fridge.", prep: "10 min", cook: "10 min", total: "20 min", yield: "4 servings", tags: ["Dinner", "Quick", "Leftovers"], color: "yellow", ingredients: [{ category: "Wok ready", items: ["2 cups cold cooked rice", "1 lb chicken, diced", "2 eggs", "Peas and carrots", "Green onions and garlic", "Neutral oil"] }, { category: "Sauce", items: ["Soy sauce", "Oyster sauce", "Sesame oil", "Black pepper"] }], steps: [{ title: "Cook the chicken", text: "Stir-fry chicken in hot oil until browned and cooked through. Move to a plate." }, { title: "Scramble and stir-fry", text: "Scramble the eggs, then cook vegetables, garlic, and green onions for a minute or two." }, { title: "Fry the rice", text: "Add cold rice and break up every clump. Let it toast before stirring too often." }, { title: "Season and finish", text: "Return chicken and eggs, add sauces, toss over high heat, then top with remaining green onion." }], note: "Cold rice is non-negotiable. Fresh rice steams itself into mush; yesterday’s rice fries beautifully." },
];

const collections = [
  { id: "All", label: "All recipes", matches: () => true },
  { id: "Dinner", label: "Dinner", matches: (recipe: Recipe) => recipe.tags.includes("Dinner") },
  { id: "Sweet", label: "Sweet treats", matches: (recipe: Recipe) => recipe.tags.includes("Sweet") },
  { id: "Drink", label: "Drinks", matches: (recipe: Recipe) => recipe.tags.includes("Drink") },
  { id: "Quick", label: "Quick & easy", matches: (recipe: Recipe) => recipe.tags.includes("Quick") },
  { id: "Baking", label: "Baking projects", matches: (recipe: Recipe) => recipe.tags.includes("Baking") },
] as const;

function recipeSearchText(recipe: Recipe) {
  return [
    recipe.title,
    recipe.subtitle,
    recipe.description,
    recipe.tags.join(" "),
    ...recipe.ingredients.flatMap((group) => [group.category, ...group.items]),
    ...recipe.steps.flatMap((step) => [step.title, step.text]),
    recipe.note,
  ].join(" ").toLowerCase();
}

export function BennyRecipeBook() {
  const [query, setQuery] = useState("");
  const [tag, setTag] = useState("All");
  const [selectedId, setSelectedId] = useState(recipes[0].id);
  const [saved, setSaved] = useState<string[]>([]);
  const [checked, setChecked] = useState<string[]>([]);
  const [mobileRecipeOpen, setMobileRecipeOpen] = useState(false);
  const selected = recipes.find((recipe) => recipe.id === selectedId) ?? recipes[0];
  const filtered = useMemo(() => {
    const activeCollection = collections.find((collection) => collection.id === tag) ?? collections[0];
    const terms = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
    return recipes
      .filter((recipe) => activeCollection.matches(recipe) && terms.every((term) => recipeSearchText(recipe).includes(term)))
      .sort((first, second) => first.title.localeCompare(second.title));
  }, [query, tag]);
  const choose = (id: string) => {
    setSelectedId(id);
    setChecked([]);
    setMobileRecipeOpen(true);
  };
  const toggleSaved = (id: string) => setSaved((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id]);
  const toggleChecked = (item: string) => setChecked((items) => items.includes(item) ? items.filter((entry) => entry !== item) : [...items, item]);

  return <main className="benny-book">
    <div className="benny-ticker" aria-hidden="true"><span>FOR BENNY · MADE AT HOME · EAT WELL · SAVE THE GOOD ONES · </span><span>FOR BENNY · MADE AT HOME · EAT WELL · SAVE THE GOOD ONES · </span></div>
    <header className="benny-header">
      <a className="benny-brand" href="#top" aria-label="Sammy's College Recipes home"><span className="benny-wordmark"><i>Dayton</i><b>Growth</b><em>Co.</em></span><span>Private recipe book</span></a>
      <div className="benny-title"><p>Recipes for</p><h1>Sammy</h1></div>
      <button className="benny-saved" onClick={() => setTag("All")}><Heart size={15} fill={saved.length ? "currentColor" : "none"} /> Saved <b>{saved.length}</b></button>
    </header>

    <section className="benny-intro" id="top">
      <p className="benny-eyebrow">The no-fuss collection</p>
      <h2>What should we make<br /><i>tonight?</i></h2>
      <p>A small collection of keepers: the comforting ones, the fast ones, and the ones worth waiting for.</p>
      <div className="benny-search"><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search dishes or ingredients" aria-label="Search recipes" />{query && <button onClick={() => setQuery("")} aria-label="Clear search"><X size={16} /></button>}</div>
    </section>

    <nav className="benny-filter" aria-label="Recipe categories">{collections.map((collection) => <button key={collection.id} className={tag === collection.id ? "active" : ""} onClick={() => setTag(collection.id)}>{collection.label}</button>)}</nav>

    <section className="benny-feature" aria-label="Selected recipe">
      <div className={`benny-photo ${selected.color}`}><img src={selected.image} alt="" /><div className="benny-sticker">{selected.tags[0]}</div><div className="benny-photo-caption">Recipe no. {String(recipes.findIndex((recipe) => recipe.id === selected.id) + 1).padStart(2, "0")}</div></div>
      <div className="benny-feature-copy">
        <button className={`benny-love ${saved.includes(selected.id) ? "is-saved" : ""}`} onClick={() => toggleSaved(selected.id)} aria-label="Save recipe"><Heart size={19} fill={saved.includes(selected.id) ? "currentColor" : "none"} /></button>
        <p className="benny-eyebrow">Make this one</p><h2>{selected.title}<span>{selected.subtitle}</span></h2><p className="benny-description">{selected.description}</p>
        <dl className="benny-stats"><div><dt>Prep</dt><dd>{selected.prep}</dd></div><div><dt>Cook</dt><dd>{selected.cook}</dd></div><div><dt>Total</dt><dd>{selected.total}</dd></div><div><dt>Makes</dt><dd>{selected.yield}</dd></div></dl>
        <a href="#recipe" className="benny-cook-button">Start cooking <ChevronRight size={18} /></a>
      </div>
    </section>

    <section className="benny-cards-section"><div className="benny-section-head"><div><p className="benny-eyebrow">The recipe box</p><h2>{tag === "All" ? "Browse the box." : collections.find((collection) => collection.id === tag)?.label}</h2></div><span>{filtered.length} recipes</span></div>
      <div className="benny-cards">{filtered.map((recipe, index) => <button className={`benny-card ${recipe.id === selected.id ? "selected" : ""}`} key={recipe.id} onClick={() => choose(recipe.id)}><div className={`benny-card-image ${recipe.color}`}><img src={recipe.image} alt="" loading={index > 2 ? "lazy" : "eager"} /><span>{recipe.total}</span></div><div><p>{recipe.tags.slice(0, 2).join(" · ")}</p><h3>{recipe.title}<small>{recipe.subtitle}</small></h3></div></button>)}</div>
      {!filtered.length && <div className="benny-empty"><Sparkles size={20} /> No recipe matches that search yet.</div>}
    </section>

    <article className="benny-recipe" id="recipe">
      <div className="benny-recipe-heading"><p className="benny-eyebrow">Now cooking</p><h2>{selected.title} <em>{selected.subtitle}</em></h2><div><button onClick={() => window.print()}><Printer size={16} /> Print</button><button onClick={() => choose(recipes[(recipes.findIndex((recipe) => recipe.id === selected.id) - 1 + recipes.length) % recipes.length].id)}><ArrowLeft size={16} /> Previous</button></div></div>
      <div className="benny-recipe-grid"><section className="benny-ingredients"><div className="benny-panel-title"><span>01</span><h3>Gather this</h3><small>{checked.length} / {selected.ingredients.flatMap((group) => group.items).length} checked</small></div>{selected.ingredients.map((group) => <div className="benny-ingredient-group" key={group.category}><h4>{group.category}</h4>{group.items.map((item, index) => { const key = `${group.category}-${index}`; const isChecked = checked.includes(key); return <label className={isChecked ? "done" : ""} key={key}><input type="checkbox" checked={isChecked} onChange={() => toggleChecked(key)} /><span><Check size={13} /></span>{item}</label>; })}</div>)}</section>
      <section className="benny-method"><div className="benny-panel-title"><span>02</span><h3>Make it happen</h3><small><Clock3 size={13} /> {selected.total}</small></div><ol>{selected.steps.map((step, index) => <li key={step.title}><b>{String(index + 1).padStart(2, "0")}</b><div><h4>{step.title}</h4><p>{step.text}</p></div></li>)}</ol><aside><Sparkles size={17} /><div><strong>Sammy's note</strong><p>{selected.note}</p></div></aside></section></div>
    </article>
    {mobileRecipeOpen && <div className="benny-mobile-sheet" role="dialog" aria-modal="true" aria-label={`${selected.title} ${selected.subtitle}`}>
      <div className="benny-mobile-sheet-header"><div><p className="benny-eyebrow">Now cooking</p><h2>{selected.title} <em>{selected.subtitle}</em></h2></div><button onClick={() => setMobileRecipeOpen(false)} aria-label="Close recipe"><X size={22} /></button></div>
      <div className="benny-mobile-sheet-meta"><span>{selected.prep} prep</span><span>{selected.cook} cook</span><span>{selected.yield}</span></div>
      <section className="benny-mobile-sheet-section"><h3>Gather this</h3>{selected.ingredients.map((group) => <div className="benny-ingredient-group" key={group.category}><h4>{group.category}</h4>{group.items.map((item, index) => { const key = `sheet-${group.category}-${index}`; const isChecked = checked.includes(key); return <label className={isChecked ? "done" : ""} key={key}><input type="checkbox" checked={isChecked} onChange={() => toggleChecked(key)} /><span><Check size={13} /></span>{item}</label>; })}</div>)}</section>
      <section className="benny-mobile-sheet-section"><h3>Make it happen</h3><ol>{selected.steps.map((step, index) => <li key={step.title}><b>{String(index + 1).padStart(2, "0")}</b><div><h4>{step.title}</h4><p>{step.text}</p></div></li>)}</ol><aside><Sparkles size={17} /><div><strong>Sammy's note</strong><p>{selected.note}</p></div></aside></section>
    </div>}
    <footer className="benny-footer"><div className="benny-mark">S<span>★</span></div><p>Made with love, and enough butter.</p><small>Sammy's College Recipes · Keep the good ones close.</small></footer>
  </main>;
}
