backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "home"
        file: "content/home.json"
        fields:
          - { label: "Headline", name: "headline", widget: "string" }
          - { label: "Subheadline", name: "subheadline", widget: "text" }
          - { label: "Phone", name: "phone", widget: "string" }
