import type { Prospect } from "./prospects";

export const partTwoProspects = [
  {
    "id": 2001,
    "industry": "Home improvement",
    "priority": 101,
    "business": "AllGood Home Improvements",
    "cityArea": "Fairfield, OH",
    "confidence": "High",
    "reviewSignal": "4 rating · 267 reviews · Established — check vendor · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Likely affordable; first qualify whether review automation already exists",
    "prospectSource": "https://www.myallgoodhome.com/contact/",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 247-2900",
    "phoneSource": "https://www.myallgoodhome.com/contact/"
  },
  {
    "id": 2002,
    "industry": "Restoration",
    "priority": 102,
    "business": "Abrams Restoration",
    "cityArea": "Batavia, OH",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 46 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://abramsrestoration.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 780-4752",
    "phoneSource": "https://abramsrestoration.com/"
  },
  {
    "id": 2003,
    "industry": "Land clearing",
    "priority": 103,
    "business": "BrushBoss",
    "cityArea": "Newbury Township, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 3 reviews · Early — qualify budget · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Validate monthly customer volume and budget before pitching",
    "prospectSource": "https://www.brushboss.co/reviews",
    "verifiedDate": "2026-09-01",
    "phone": "(440) 557-4660",
    "phoneSource": "https://www.brushboss.co/reviews"
  },
  {
    "id": 2004,
    "industry": "Tree service",
    "priority": 104,
    "business": "Ghost Tree Service",
    "cityArea": "Seville, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 48 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.ghosttreeservice.com/quote/",
    "verifiedDate": "2026-09-01",
    "phone": "(330) 907-6403",
    "phoneSource": "https://www.ghosttreeservice.com/quote/"
  },
  {
    "id": 2005,
    "industry": "Landscaping",
    "priority": 105,
    "business": "Our 6 Landscaping",
    "cityArea": "Westlake, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.our6landscaping.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(216) 903-0299",
    "phoneSource": "https://www.our6landscaping.com/"
  },
  {
    "id": 2006,
    "industry": "Roofing and restoration",
    "priority": 106,
    "business": "Atlas Roofing & Restoration",
    "cityArea": "Beachwood, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://atlasroofingrestoration.com/residential-roofing/",
    "verifiedDate": "2026-09-01",
    "phone": "(216) 888-3208",
    "phoneSource": "https://atlasroofingrestoration.com/residential-roofing/"
  },
  {
    "id": 2007,
    "industry": "Electrical",
    "priority": 107,
    "business": "Benrishi Electrical",
    "cityArea": "West Chester, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 173 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.benrishico.com/outlet-installation/",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 813-7988",
    "phoneSource": "https://www.benrishico.com/outlet-installation/"
  },
  {
    "id": 2008,
    "industry": "Painting",
    "priority": 108,
    "business": "Right Way Painting",
    "cityArea": "Northeast Ohio",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://file.realproducersmagazine.com/issue/2023_Dec_Real_Producers_Cleveland.pdf",
    "verifiedDate": "2026-09-01",
    "phone": "(330) 815-5615",
    "phoneSource": "https://file.realproducersmagazine.com/issue/2023_Dec_Real_Producers_Cleveland.pdf"
  },
  {
    "id": 2009,
    "industry": "Excavation and home improvement",
    "priority": 109,
    "business": "Jordan Home Improvement",
    "cityArea": "Athens, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.ci.athens.oh.us/596/Fall-2025-Program-Guide",
    "verifiedDate": "2026-09-01",
    "phone": "(740) 249-9337",
    "phoneSource": "https://www.ci.athens.oh.us/596/Fall-2025-Program-Guide"
  },
  {
    "id": 2010,
    "industry": "Plumbing",
    "priority": 110,
    "business": "On Point Plumbing",
    "cityArea": "Greenwood, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://onpointplumbingindy.com/contact/",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 496-9915",
    "phoneSource": "https://onpointplumbingindy.com/contact/"
  },
  {
    "id": 2011,
    "industry": "HVAC",
    "priority": 111,
    "business": "Honeycutt Heating & Cooling",
    "cityArea": "Southeast Michigan",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.honeycuttheating.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(313) 335-7020",
    "phoneSource": "https://www.honeycuttheating.com/"
  },
  {
    "id": 2012,
    "industry": "Junk removal",
    "priority": 112,
    "business": "Purge Pros",
    "cityArea": "Indianapolis, IN",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://itspurgepros.com/reviews",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 961-5865",
    "phoneSource": "https://itspurgepros.com/reviews"
  },
  {
    "id": 2013,
    "industry": "Cleaning services",
    "priority": 113,
    "business": "Mess To Impress Cleaning",
    "cityArea": "Indianapolis, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.messtoimpresscleaning.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 992-4609",
    "phoneSource": "https://www.messtoimpresscleaning.com/"
  },
  {
    "id": 2014,
    "industry": "Landscaping",
    "priority": 114,
    "business": "Tri-Point Landscaping",
    "cityArea": "Macomb County, MI",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.tripointlandscaping.com/testimonials",
    "verifiedDate": "2026-09-01",
    "phone": "(586) 327-8080",
    "phoneSource": "https://www.tripointlandscaping.com/testimonials"
  },
  {
    "id": 2015,
    "industry": "Landscaping",
    "priority": 115,
    "business": "Grounds to Gardens",
    "cityArea": "Dexter / Ann Arbor, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 35 reviews · Ideal band · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.groundstogardens.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(734) 945-7441",
    "phoneSource": "https://www.groundstogardens.com/"
  },
  {
    "id": 2016,
    "industry": "Cleaning services",
    "priority": 116,
    "business": "The Cleaning Crew",
    "cityArea": "Zionsville / Indianapolis, IN",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.thecleaningcrewindy.com/google-reviews",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 748-0059",
    "phoneSource": "https://www.thecleaningcrewindy.com/google-reviews"
  },
  {
    "id": 2017,
    "industry": "Roofing and exteriors",
    "priority": 117,
    "business": "Reliant Exteriors",
    "cityArea": "St. Louis, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 24 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://reliant-exteriors.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(314) 529-0131",
    "phoneSource": "https://reliant-exteriors.com/"
  },
  {
    "id": 2018,
    "industry": "Roofing and construction",
    "priority": 118,
    "business": "Cline Construction & Roofing",
    "cityArea": "Pleasant Hill, MO",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 60 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.clineconstructionandroofing.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(816) 540-2634",
    "phoneSource": "https://www.clineconstructionandroofing.com/"
  },
  {
    "id": 2019,
    "industry": "Lawn care",
    "priority": 119,
    "business": "Eastern Iowa Lawn Care",
    "cityArea": "Maquoketa, IA",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 39 reviews · Ideal band · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://easternialawncare.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(563) 258-7390",
    "phoneSource": "https://easternialawncare.com/"
  },
  {
    "id": 2020,
    "industry": "Cleaning services",
    "priority": 120,
    "business": "Code 3 Cleaning",
    "cityArea": "Pleasant Prairie, WI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://code3cleaners.com/contact/",
    "verifiedDate": "2026-09-01",
    "phone": "(224) 381-0033",
    "phoneSource": "https://code3cleaners.com/contact/"
  },
  {
    "id": 2021,
    "industry": "Landscaping",
    "priority": 121,
    "business": "Hatcher's Lawn & Landscaping",
    "cityArea": "Omaha, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://hatcherslawn-landscaping.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(402) 301-1880",
    "phoneSource": "https://hatcherslawn-landscaping.com/"
  },
  {
    "id": 2022,
    "industry": "Home services",
    "priority": 122,
    "business": "Brandau Home Services",
    "cityArea": "Chicagoland, IL",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://brandauhomeservices.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(815) 800-2557",
    "phoneSource": "https://brandauhomeservices.com/"
  },
  {
    "id": 2023,
    "industry": "Lawn care",
    "priority": 123,
    "business": "Legacy Lawns",
    "cityArea": "Lincoln, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://legacy-lawns.b12sites.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(531) 530-9246",
    "phoneSource": "https://legacy-lawns.b12sites.com/"
  },
  {
    "id": 2024,
    "industry": "Construction",
    "priority": 124,
    "business": "Hols & Co LLC",
    "cityArea": "Harrisburg / Sioux Falls, SD",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://holsco.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(605) 679-5223",
    "phoneSource": "https://holsco.com/"
  },
  {
    "id": 2025,
    "industry": "Exterior cleaning",
    "priority": 125,
    "business": "Pane Pal",
    "cityArea": "Palatine, IL",
    "confidence": "High",
    "reviewSignal": "5 rating · 92 reviews · Ideal band · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://panepal.us/",
    "verifiedDate": "2026-09-01",
    "phone": "(224) 458-2496",
    "phoneSource": "https://panepal.us/"
  },
  {
    "id": 2026,
    "industry": "HVAC",
    "priority": 126,
    "business": "SuperTec Heating & Cooling",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 173 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.homeadvisor.com/rated.SuperTecHeating.45599084.html",
    "verifiedDate": "2026-09-01",
    "phone": "(614) 595-9251",
    "phoneSource": "https://www.homeadvisor.com/rated.SuperTecHeating.45599084.html"
  },
  {
    "id": 2027,
    "industry": "General contracting",
    "priority": 127,
    "business": "Angry Cat Contracting",
    "cityArea": "Howell / Metro Detroit, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 28 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://angrycatcontracting.com/contact",
    "verifiedDate": "2026-09-01",
    "phone": "(734) 756-5844",
    "phoneSource": "https://angrycatcontracting.com/contact"
  },
  {
    "id": 2028,
    "industry": "Plumbing and HVAC",
    "priority": 128,
    "business": "Quality Control Plumbing Heating & Air",
    "cityArea": "Indianapolis, IN",
    "confidence": "High",
    "reviewSignal": "36 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.qcplumbingheatingandair.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 435-6608",
    "phoneSource": "https://www.qcplumbingheatingandair.com/"
  },
  {
    "id": 2029,
    "industry": "Construction",
    "priority": 129,
    "business": "Fifi's Construction",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.fifisconstruction.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(220) 238-0513",
    "phoneSource": "https://www.fifisconstruction.com/"
  },
  {
    "id": 2030,
    "industry": "Electrical",
    "priority": 130,
    "business": "Buckeye Electric",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.buckeyeelectric.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(614) 664-8800",
    "phoneSource": "https://www.buckeyeelectric.com/"
  },
  {
    "id": 2031,
    "industry": "Construction",
    "priority": 131,
    "business": "Oak & Mason Construction",
    "cityArea": "Indianapolis, IN",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.oakandmason.com/contact",
    "verifiedDate": "2026-09-01",
    "phone": "(317) 353-4792",
    "phoneSource": "https://www.oakandmason.com/contact"
  },
  {
    "id": 2032,
    "industry": "Mattress retail",
    "priority": 132,
    "business": "Mattress Warehouse of Central Ohio",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://file.realproducersmagazine.com/issue/2025_Jun_Real_Producers_Columbus.pdf",
    "verifiedDate": "2026-09-01",
    "phone": "(614) 468-3070",
    "phoneSource": "https://file.realproducersmagazine.com/issue/2025_Jun_Real_Producers_Columbus.pdf"
  },
  {
    "id": 2033,
    "industry": "Mobile auto detailing",
    "priority": 133,
    "business": "Street Standard Detailing",
    "cityArea": "Des Moines, IA",
    "confidence": "High",
    "reviewSignal": "5 rating · 27 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://streetstandarddetailing.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(515) 360-6110",
    "phoneSource": "https://streetstandarddetailing.com/"
  },
  {
    "id": 2034,
    "industry": "Insurance agency",
    "priority": 134,
    "business": "Terry Taylor State Farm",
    "cityArea": "Des Moines, IA",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "High-value local decisions depend heavily on visible trust and recent client experiences.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.terryanntaylor.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(515) 274-3444",
    "phoneSource": "https://www.terryanntaylor.com/"
  },
  {
    "id": 2035,
    "industry": "Mobile device repair",
    "priority": 135,
    "business": "Tech Medic Mobile Repair",
    "cityArea": "Twin Cities, MN",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://techmedicmobile.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(952) 206-4337",
    "phoneSource": "https://techmedicmobile.com/"
  },
  {
    "id": 2036,
    "industry": "Electrical",
    "priority": 136,
    "business": "Spark Shark",
    "cityArea": "Milwaukee, WI",
    "confidence": "High",
    "reviewSignal": "35 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://spark-shark.com/services/remodeling/",
    "verifiedDate": "2026-09-01",
    "phone": "(262) 587-5887",
    "phoneSource": "https://spark-shark.com/services/remodeling/"
  },
  {
    "id": 2037,
    "industry": "Party rentals",
    "priority": 137,
    "business": "Bounce n Jump a Rama",
    "cityArea": "Milwaukee, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 260 reviews · Established — check vendor · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Likely affordable; first qualify whether review automation already exists",
    "prospectSource": "https://bouncenjumparama.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(414) 403-9036",
    "phoneSource": "https://bouncenjumparama.com/"
  },
  {
    "id": 2038,
    "industry": "IT and security",
    "priority": 138,
    "business": "Frankie OnCall",
    "cityArea": "Kansas City, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 331 reviews · Established — check vendor · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Likely affordable; first qualify whether review automation already exists",
    "prospectSource": "https://www.frankieoncall.com/contact-us/",
    "verifiedDate": "2026-09-01",
    "phone": "(816) 788-4999",
    "phoneSource": "https://www.frankieoncall.com/contact-us/"
  },
  {
    "id": 2039,
    "industry": "HVAC",
    "priority": 139,
    "business": "Des Moines Comfort",
    "cityArea": "Des Moines, IA",
    "confidence": "High",
    "reviewSignal": "5 rating · 200 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://desmoinescomfort.com/about/",
    "verifiedDate": "2026-09-01",
    "phone": "(515) 266-4660",
    "phoneSource": "https://desmoinescomfort.com/about/"
  },
  {
    "id": 2040,
    "industry": "Mobile auto repair",
    "priority": 140,
    "business": "Des Moines Mobile Mechanics",
    "cityArea": "Des Moines, IA",
    "confidence": "High",
    "reviewSignal": "5 rating · 24 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://desmoinesmechanics.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(515) 326-5563",
    "phoneSource": "https://desmoinesmechanics.com/"
  },
  {
    "id": 2041,
    "industry": "Sewer inspection",
    "priority": 141,
    "business": "Sewer Doctors",
    "cityArea": "Kansas City, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://file.realproducersmagazine.com/issue/2024_Apr_Real_Producers_Kansas_City.pdf",
    "verifiedDate": "2026-09-01",
    "phone": "(816) 888-0750",
    "phoneSource": "https://file.realproducersmagazine.com/issue/2024_Apr_Real_Producers_Kansas_City.pdf"
  },
  {
    "id": 2042,
    "industry": "Roofing and remodeling",
    "priority": 142,
    "business": "Leader Construction Company",
    "cityArea": "St. Louis, MO",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.leaderconstructioncompany.com/roofing-and-siding-services",
    "verifiedDate": "2026-09-01",
    "phone": "(314) 604-3999",
    "phoneSource": "https://www.leaderconstructioncompany.com/roofing-and-siding-services"
  },
  {
    "id": 2043,
    "industry": "House cleaning",
    "priority": 143,
    "business": "Super Clean Home Services",
    "cityArea": "Chicago, IL",
    "confidence": "High",
    "reviewSignal": "5 rating · 200 reviews · Ideal band · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://chicago-maidservices.com/avondale-house-cleaning/",
    "verifiedDate": "2026-09-01",
    "phone": "(773) 575-6004",
    "phoneSource": "https://chicago-maidservices.com/avondale-house-cleaning/"
  },
  {
    "id": 2044,
    "industry": "Lawn care",
    "priority": 144,
    "business": "Orchard Lawn Solutions",
    "cityArea": "Metro Detroit, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 43 reviews · Ideal band · publicly invites texts",
    "fitReason": "Frequent completed visits can produce steady review velocity and stronger local-map conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.orchardlawnaeration.com/reviews/",
    "verifiedDate": "2026-09-01",
    "phone": "(248) 226-0798",
    "phoneSource": "https://www.orchardlawnaeration.com/reviews/"
  },
  {
    "id": 2045,
    "industry": "Garage doors and appliance repair",
    "priority": 145,
    "business": "ABS Home Services",
    "cityArea": "St. Louis, MO",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://abshomeservices.com/garage-door-service/",
    "verifiedDate": "2026-09-01",
    "phone": "(314) 440-5132",
    "phoneSource": "https://abshomeservices.com/garage-door-service/"
  },
  {
    "id": 2046,
    "industry": "Concrete",
    "priority": 146,
    "business": "Mitten Made Concrete",
    "cityArea": "Metro Detroit, MI",
    "confidence": "High",
    "reviewSignal": "4.5 rating · 15 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://mittenmadeconcrete.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(586) 447-6135",
    "phoneSource": "https://mittenmadeconcrete.com/"
  },
  {
    "id": 2047,
    "industry": "Garage doors",
    "priority": 147,
    "business": "Stucky's Garage Doors",
    "cityArea": "Wentzville, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 131 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.stuckysgaragedoors.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(314) 280-6182",
    "phoneSource": "https://www.stuckysgaragedoors.com/"
  },
  {
    "id": 2048,
    "industry": "Mattress retail",
    "priority": 148,
    "business": "Mattress by Appointment Sedalia",
    "cityArea": "Sedalia, MO",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://cdn1.creativecirclemedia.com/sedalia/files/20210828-030030-SED%2008-28-2021.pdf",
    "verifiedDate": "2026-09-01",
    "phone": "(660) 619-7595",
    "phoneSource": "https://cdn1.creativecirclemedia.com/sedalia/files/20210828-030030-SED%2008-28-2021.pdf"
  },
  {
    "id": 2049,
    "industry": "Auto repair",
    "priority": 149,
    "business": "NRG Automotive Repair",
    "cityArea": "Madison, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://www.nrgautomadison.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(608) 335-8680",
    "phoneSource": "https://www.nrgautomadison.com/"
  },
  {
    "id": 2050,
    "industry": "Mortgage broker",
    "priority": 150,
    "business": "Adam Zeman Mortgage Team",
    "cityArea": "Madison, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 26 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions depend heavily on visible trust and recent client experiences.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://adamzmortgageteam.com/mortgage-broker-madison-wi/",
    "verifiedDate": "2026-09-01",
    "phone": "(414) 975-2654",
    "phoneSource": "https://adamzmortgageteam.com/mortgage-broker-madison-wi/"
  },
  {
    "id": 2051,
    "industry": "Plumbing",
    "priority": 151,
    "business": "McGuire Plumbing",
    "cityArea": "Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 148 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.mcguireplumbingllc.com/quote",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 293-9664",
    "phoneSource": "https://www.mcguireplumbingllc.com/quote"
  },
  {
    "id": 2052,
    "industry": "Used car dealer",
    "priority": 152,
    "business": "Legacy Automotive",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "4.7 rating · Verify count · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://legacydeals.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(614) 580-1291",
    "phoneSource": "https://legacydeals.com/"
  },
  {
    "id": 2053,
    "industry": "Outdoor services",
    "priority": 153,
    "business": "Mike's Outdoor Services",
    "cityArea": "Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 31 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.mikesoutdoorservices.biz/",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 259-3817",
    "phoneSource": "https://www.mikesoutdoorservices.biz/"
  },
  {
    "id": 2054,
    "industry": "Moving company",
    "priority": 154,
    "business": "608 Movers",
    "cityArea": "Madison, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 247 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://608movers.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(608) 855-4007",
    "phoneSource": "https://608movers.com/"
  },
  {
    "id": 2055,
    "industry": "Chimney and masonry",
    "priority": 155,
    "business": "A1 Chimney & Masonry",
    "cityArea": "Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 38 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.cincinnatichimneyservices.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(513) 382-0530",
    "phoneSource": "https://www.cincinnatichimneyservices.com/"
  },
  {
    "id": 2056,
    "industry": "Roofing and renovation",
    "priority": 156,
    "business": "JM Renovations LLC",
    "cityArea": "Madison, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 12 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://jmrenovations.net/",
    "verifiedDate": "2026-09-01",
    "phone": "(608) 520-2258",
    "phoneSource": "https://jmrenovations.net/"
  },
  {
    "id": 2057,
    "industry": "Real estate",
    "priority": 157,
    "business": "Mo Plank Realtor",
    "cityArea": "Columbus, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 57 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions depend heavily on visible trust and recent client experiences.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.moplankrealtor.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(614) 203-2918",
    "phoneSource": "https://www.moplankrealtor.com/"
  },
  {
    "id": 2058,
    "industry": "Auto repair",
    "priority": 158,
    "business": "Europros",
    "cityArea": "Wichita, KS",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 110 reviews · Ideal band · publicly invites texts",
    "fitReason": "Each completed job creates a clear review-request moment, and one extra local-search lead can be valuable.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://www.europrosllc.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(316) 250-5900",
    "phoneSource": "https://www.europrosllc.com/"
  },
  {
    "id": 2059,
    "industry": "Fence contractor",
    "priority": 159,
    "business": "Midwest Fence",
    "cityArea": "Wichita, KS",
    "confidence": "High",
    "reviewSignal": "5 rating · 232 reviews · Ideal band · publicly invites texts",
    "fitReason": "Local buyers compare visible reputation before contacting; consistent recent reviews can lift trust and conversion.",
    "qualificationNote": "Good balance of proven demand and meaningful review headroom",
    "prospectSource": "https://midwestfenceict.com/contact/",
    "verifiedDate": "2026-09-01",
    "phone": "(316) 710-5824",
    "phoneSource": "https://midwestfenceict.com/contact/"
  },
  {
    "id": 2060,
    "industry": "Veterinary clinic",
    "priority": 160,
    "business": "Sunflower Veterinary Care Clinic",
    "cityArea": "Wichita, KS",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Recent reviews reduce trust friction for appointment-driven local decisions; requests must stay privacy-safe.",
    "qualificationNote": "Confirm current Google/Facebook count and decision-maker before outreach",
    "prospectSource": "https://svccict.com/",
    "verifiedDate": "2026-09-01",
    "phone": "(316) 524-3257",
    "phoneSource": "https://svccict.com/"
  }
] satisfies Prospect[];
