import type { Prospect } from "./prospects";

export const replacementProspects = [
  {
    "id": 1001,
    "industry": "Mobile notary",
    "priority": 1,
    "business": "Signed On Time Mobile Notary",
    "cityArea": "Waynesville, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.signedontime.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 226-9052",
    "phoneSource": "https://www.signedontime.com/contact"
  },
  {
    "id": 1002,
    "industry": "Remodeling",
    "priority": 2,
    "business": "Fullard Quality Renovations",
    "cityArea": "Toledo, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.bladehomes.com/wp-content/uploads/2025/08/RET-08212025.pdf",
    "verifiedDate": "2026-08-31",
    "phone": "(567) 395-8149",
    "phoneSource": "https://www.bladehomes.com/wp-content/uploads/2025/08/RET-08212025.pdf"
  },
  {
    "id": 1003,
    "industry": "IT services",
    "priority": 3,
    "business": "CORCENT",
    "cityArea": "Gahanna, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.corcent.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 289-8000",
    "phoneSource": "https://www.corcent.com/"
  },
  {
    "id": 1004,
    "industry": "Marketing agency",
    "priority": 4,
    "business": "Upward Digital Marketing Group",
    "cityArea": "Westerville, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.upwarddigitalmarketing.com/contact/",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 699-3010",
    "phoneSource": "https://www.upwarddigitalmarketing.com/contact/"
  },
  {
    "id": 1005,
    "industry": "Remodeling",
    "priority": 5,
    "business": "Ohio Home Doctor",
    "cityArea": "Dayton, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.trustindex.io/reviews/www.ohiohomedoctorremodeling.com",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 605-6882",
    "phoneSource": "https://www.trustindex.io/reviews/www.ohiohomedoctorremodeling.com"
  },
  {
    "id": 1006,
    "industry": "Remodeling",
    "priority": 6,
    "business": "Elite Building & Remodeling",
    "cityArea": "Madison, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.elitebuildbright.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(440) 417-6930",
    "phoneSource": "https://www.elitebuildbright.com/"
  },
  {
    "id": 1007,
    "industry": "Marketing agency",
    "priority": 7,
    "business": "Adept Creative",
    "cityArea": "Cleveland, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://adeptcreative.com/contact/",
    "verifiedDate": "2026-08-31",
    "phone": "(216) 452-6559",
    "phoneSource": "https://adeptcreative.com/contact/"
  },
  {
    "id": 1008,
    "industry": "Accounting and tax",
    "priority": 8,
    "business": "CP & A Tax Services Company",
    "cityArea": "Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.cpataxservicescompany.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 512-4777",
    "phoneSource": "https://www.cpataxservicescompany.com/"
  },
  {
    "id": 1009,
    "industry": "Med spa and aesthetics",
    "priority": 9,
    "business": "Handcrafted Aesthetics & Medical Spa",
    "cityArea": "Gahanna, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Appointment completion creates a repeatable, privacy-sensitive review request trigger.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.handcraftedaesthetics.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 999-0384",
    "phoneSource": "https://www.handcraftedaesthetics.com/contact"
  },
  {
    "id": 1010,
    "industry": "Home improvement",
    "priority": 10,
    "business": "Energy Plus Home Improvements",
    "cityArea": "Alma, MI",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://energyplushomeimprovements.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(989) 833-1000",
    "phoneSource": "https://energyplushomeimprovements.com/"
  },
  {
    "id": 1011,
    "industry": "Landscaping",
    "priority": 11,
    "business": "Blackstone Landscaping",
    "cityArea": "Southeast Michigan",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 32 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.blackstonelandscaping.com/leading-landscaping-contractor-blackstone-se-michigan/",
    "verifiedDate": "2026-08-31",
    "phone": "(248) 939-3600",
    "phoneSource": "https://www.blackstonelandscaping.com/leading-landscaping-contractor-blackstone-se-michigan/"
  },
  {
    "id": 1012,
    "industry": "HVAC",
    "priority": 12,
    "business": "Wiegand & Sons HVAC",
    "cityArea": "Muskegon, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://wiegandandsonshvac.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 566-0921",
    "phoneSource": "https://wiegandandsonshvac.com/"
  },
  {
    "id": 1013,
    "industry": "Home builder",
    "priority": 13,
    "business": "All American Home Builders",
    "cityArea": "Grass Lake, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.allamericanhomebuilders.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(517) 206-3175",
    "phoneSource": "https://www.allamericanhomebuilders.com/"
  },
  {
    "id": 1014,
    "industry": "Roofing and restoration",
    "priority": 14,
    "business": "Saia & Sons Restoration",
    "cityArea": "Crown Point, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.saiarestoration.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(219) 209-2433",
    "phoneSource": "https://www.saiarestoration.com/"
  },
  {
    "id": 1015,
    "industry": "Electrical",
    "priority": 15,
    "business": "Sumnicht Electric",
    "cityArea": "Neenah, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 50 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://sumnichtelectric.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(920) 268-2509",
    "phoneSource": "https://sumnichtelectric.com/"
  },
  {
    "id": 1016,
    "industry": "Real estate",
    "priority": 16,
    "business": "Rennie Barton Team",
    "cityArea": "Grandville, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 37 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://renniebartonluxury.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 856-1492",
    "phoneSource": "https://renniebartonluxury.com/"
  },
  {
    "id": 1017,
    "industry": "Electrical",
    "priority": 17,
    "business": "Elite Electrical Solutions",
    "cityArea": "Lawrenceburg, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 130 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.eliteelectrical.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 502-4780",
    "phoneSource": "https://www.eliteelectrical.com/contact"
  },
  {
    "id": 1018,
    "industry": "Plumbing",
    "priority": 18,
    "business": "Dearborn Plumbing",
    "cityArea": "Dearborn, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://dearbornsplumber.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(313) 614-6818",
    "phoneSource": "https://dearbornsplumber.com/"
  },
  {
    "id": 1019,
    "industry": "Electrical",
    "priority": 19,
    "business": "JCH Electric",
    "cityArea": "White Cloud, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.jchelectric.net/",
    "verifiedDate": "2026-08-31",
    "phone": "(231) 250-2099",
    "phoneSource": "https://www.jchelectric.net/"
  },
  {
    "id": 1020,
    "industry": "Roofing and remodeling",
    "priority": 20,
    "business": "Kohlfeld Contracting",
    "cityArea": "Mehlville, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 15 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.kohlfeldcontracting.com/about-us",
    "verifiedDate": "2026-08-31",
    "phone": "(314) 329-1873",
    "phoneSource": "https://www.kohlfeldcontracting.com/about-us"
  },
  {
    "id": 1021,
    "industry": "Landscaping",
    "priority": 21,
    "business": "Soriano's Landscaping",
    "cityArea": "Kansas City, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 24 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://sorianoslandscaping.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(816) 874-9554",
    "phoneSource": "https://sorianoslandscaping.com/"
  },
  {
    "id": 1022,
    "industry": "Trenchless plumbing",
    "priority": 22,
    "business": "Gustum Trenchless Repair",
    "cityArea": "Sand Creek, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 10 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://gustumtrenchless.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(715) 658-6070",
    "phoneSource": "https://gustumtrenchless.com/"
  },
  {
    "id": 1023,
    "industry": "Roofing and siding",
    "priority": 23,
    "business": "New Beginning Exteriors",
    "cityArea": "Saint Paul, MN",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.newbeginningexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 741-5569",
    "phoneSource": "https://www.newbeginningexteriors.com/"
  },
  {
    "id": 1024,
    "industry": "Remodeling",
    "priority": 24,
    "business": "Dawson Contracting",
    "cityArea": "Marshall, MO",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://dawsoncontracting.com/index.html",
    "verifiedDate": "2026-08-31",
    "phone": "(660) 886-8521",
    "phoneSource": "https://dawsoncontracting.com/index.html"
  },
  {
    "id": 1025,
    "industry": "Roofing and siding",
    "priority": 25,
    "business": "Advanced Roofing & Siding",
    "cityArea": "Oak Grove, MN",
    "confidence": "High",
    "reviewSignal": "5 rating · 175 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.advancedroofingmn.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(763) 427-3039",
    "phoneSource": "https://www.advancedroofingmn.com/"
  },
  {
    "id": 1026,
    "industry": "Mobile diesel repair",
    "priority": 26,
    "business": "Mudhollow Mobile Diesel Mechanics",
    "cityArea": "Western Iowa",
    "confidence": "High",
    "reviewSignal": "5 rating · 58 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://mudhollowdieselmechanics.com/testimonials/",
    "verifiedDate": "2026-08-31",
    "phone": "(712) 827-0207",
    "phoneSource": "https://mudhollowdieselmechanics.com/testimonials/"
  },
  {
    "id": 1027,
    "industry": "Roofing and remodeling",
    "priority": 27,
    "business": "Innovative Building & Design",
    "cityArea": "Blaine, MN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://innovativebuilding.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 808-6025",
    "phoneSource": "https://innovativebuilding.com/"
  },
  {
    "id": 1028,
    "industry": "Plumbing",
    "priority": 28,
    "business": "Posey Family Plumbing",
    "cityArea": "Washington, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 127 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.poseyfamilyplumbing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(314) 620-4809",
    "phoneSource": "https://www.poseyfamilyplumbing.com/"
  },
  {
    "id": 1029,
    "industry": "Plumbing and electrical",
    "priority": 29,
    "business": "Midway Electric",
    "cityArea": "Columbia, MO",
    "confidence": "High",
    "reviewSignal": "4.8 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.midwayelectricinc.com/plumbing/",
    "verifiedDate": "2026-08-31",
    "phone": "(573) 446-2484",
    "phoneSource": "https://www.midwayelectricinc.com/plumbing/"
  },
  {
    "id": 1030,
    "industry": "Tree service",
    "priority": 30,
    "business": "The Industry Standard Tree Service",
    "cityArea": "Fort Wayne, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 31 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://tistrees.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(260) 298-1652",
    "phoneSource": "https://tistrees.com/"
  },
  {
    "id": 1031,
    "industry": "Carpet cleaning",
    "priority": 31,
    "business": "Meyer Carpet Cleaning",
    "cityArea": "West Bend, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 91 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.meyercarpetcleaning.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(414) 610-9507",
    "phoneSource": "https://www.meyercarpetcleaning.com/"
  },
  {
    "id": 1032,
    "industry": "Pressure washing",
    "priority": 32,
    "business": "Redhead Pressure Cleaning",
    "cityArea": "Springboro, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 55 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://redheadpressurecleaning.com/reviews",
    "verifiedDate": "2026-08-31",
    "phone": "(351) 242-0666",
    "phoneSource": "https://redheadpressurecleaning.com/reviews"
  },
  {
    "id": 1033,
    "industry": "Dumpster rental",
    "priority": 33,
    "business": "J's Dumpster Rentals",
    "cityArea": "Richmond, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 119 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://richmonddumpstersin.com/contact.html",
    "verifiedDate": "2026-08-31",
    "phone": "(765) 238-1393",
    "phoneSource": "https://richmonddumpstersin.com/contact.html"
  },
  {
    "id": 1034,
    "industry": "Home inspection",
    "priority": 34,
    "business": "Wolf Inspectors",
    "cityArea": "Greater Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.wolfhomeinspector.com/reviews.html",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 720-9100",
    "phoneSource": "https://www.wolfhomeinspector.com/reviews.html"
  },
  {
    "id": 1035,
    "industry": "Mobile auto detailing",
    "priority": 35,
    "business": "444 Mobile Detailing",
    "cityArea": "Wixom, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 6 reviews · Too early / qualify · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Emerging business; verify budget and monthly customer volume",
    "prospectSource": "https://444mobiledetailing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(810) 844-9137",
    "phoneSource": "https://444mobiledetailing.com/"
  },
  {
    "id": 1036,
    "industry": "Exterior cleaning",
    "priority": 36,
    "business": "Elevation Exterior Cleaning",
    "cityArea": "Wyoming, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 49 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://elevationexteriorcleaning.com/commercial-exterior-cleaning-rockford/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 229-0625",
    "phoneSource": "https://elevationexteriorcleaning.com/commercial-exterior-cleaning-rockford/"
  },
  {
    "id": 1037,
    "industry": "Cleaning services",
    "priority": 37,
    "business": "Watkins Cleaning Company",
    "cityArea": "Southeast Michigan",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.michiganfcs.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(248) 225-5027",
    "phoneSource": "https://www.michiganfcs.com/contact"
  },
  {
    "id": 1038,
    "industry": "Mobile auto detailing",
    "priority": 38,
    "business": "CJM Mobile Detailing",
    "cityArea": "Byron Center, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 49 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://cjmautodetailing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 801-4439",
    "phoneSource": "https://cjmautodetailing.com/"
  },
  {
    "id": 1039,
    "industry": "Auto audio tint detailing",
    "priority": 39,
    "business": "Rewired Mobile Solutions",
    "cityArea": "Racine, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://rewiredmobilesolutions.org/",
    "verifiedDate": "2026-08-31",
    "phone": "(262) 554-1202",
    "phoneSource": "https://rewiredmobilesolutions.org/"
  },
  {
    "id": 1040,
    "industry": "Carpet cleaning",
    "priority": 40,
    "business": "Hi Tek Professional Carpet Care",
    "cityArea": "Lake Geneva, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 100 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.hitekprofessionalcarpetcare.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(262) 995-5085",
    "phoneSource": "https://www.hitekprofessionalcarpetcare.com/"
  },
  {
    "id": 1041,
    "industry": "Pressure washing",
    "priority": 41,
    "business": "Fishers Power Washing",
    "cityArea": "Fishers, IN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 45 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.fisherspowerwashing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(317) 572-7061",
    "phoneSource": "https://www.fisherspowerwashing.com/"
  },
  {
    "id": 1042,
    "industry": "House cleaning",
    "priority": 42,
    "business": "Xtra Mile Cleaning",
    "cityArea": "Bay County, MI",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 14 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://extra-mile-cleaning.lovable.app/",
    "verifiedDate": "2026-08-31",
    "phone": "(810) 336-4890",
    "phoneSource": "https://extra-mile-cleaning.lovable.app/"
  },
  {
    "id": 1043,
    "industry": "Home technology",
    "priority": 43,
    "business": "Simplified Tech",
    "cityArea": "Minnesota",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.simplifiedtech.io/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 567-8567",
    "phoneSource": "https://www.simplifiedtech.io/contact"
  },
  {
    "id": 1044,
    "industry": "Auto repair",
    "priority": 44,
    "business": "DAVID's Auto Care",
    "cityArea": "Sioux Falls, SD",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 84 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://davidsautocare.com/reviews/",
    "verifiedDate": "2026-08-31",
    "phone": "(605) 929-7027",
    "phoneSource": "https://davidsautocare.com/reviews/"
  },
  {
    "id": 1045,
    "industry": "Auto detailing",
    "priority": 45,
    "business": "MC Auto Detailing",
    "cityArea": "Lincoln, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 80 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://mcautodetailinglincoln.com/reviews",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 525-7201",
    "phoneSource": "https://mcautodetailinglincoln.com/reviews"
  },
  {
    "id": 1046,
    "industry": "Junk removal",
    "priority": 46,
    "business": "Fuzed Enterprises",
    "cityArea": "Omaha, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 80 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://fuzedenterprises.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 709-1531",
    "phoneSource": "https://fuzedenterprises.com/"
  },
  {
    "id": 1047,
    "industry": "Self storage",
    "priority": 47,
    "business": "Superior Storage",
    "cityArea": "St. Michael, MN",
    "confidence": "High",
    "reviewSignal": "4 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.selfstorage-us.com/about",
    "verifiedDate": "2026-08-31",
    "phone": "(763) 200-6443",
    "phoneSource": "https://www.selfstorage-us.com/about"
  },
  {
    "id": 1048,
    "industry": "Custom home builder",
    "priority": 48,
    "business": "Choice Custom Homes",
    "cityArea": "Elkhorn, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 54 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://choicecustomhomesne.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 850-1186",
    "phoneSource": "https://choicecustomhomesne.com/"
  },
  {
    "id": 1049,
    "industry": "Roofing and exteriors",
    "priority": 49,
    "business": "Statement Exteriors",
    "cityArea": "Omaha, NE",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 200 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://statementext.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 915-4245",
    "phoneSource": "https://statementext.com/"
  },
  {
    "id": 1050,
    "industry": "Real estate",
    "priority": 50,
    "business": "Dan Salamone Realtor",
    "cityArea": "New Hope, MN",
    "confidence": "High",
    "reviewSignal": "5 rating · 15 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://dansalamonerealtor.com/2026/02/01/read-this-before-you-sell-to-homestead-road/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 404-9708",
    "phoneSource": "https://dansalamonerealtor.com/2026/02/01/read-this-before-you-sell-to-homestead-road/"
  },
  {
    "id": 1051,
    "industry": "Exterior cleaning",
    "priority": 51,
    "business": "Vitality Pro Wash",
    "cityArea": "Bloomington, MN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 121 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://vitalityprowash.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 644-8870",
    "phoneSource": "https://vitalityprowash.com/"
  },
  {
    "id": 1052,
    "industry": "Home inspection",
    "priority": 52,
    "business": "Comfort Home Inspections",
    "cityArea": "Minnesota",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.comforthomeinspections.net/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 469-9707",
    "phoneSource": "https://www.comforthomeinspections.net/"
  },
  {
    "id": 1053,
    "industry": "Exterior cleaning",
    "priority": 53,
    "business": "Happy House Exteriors",
    "cityArea": "Springfield, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 160 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://happyhouseexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(417) 766-8666",
    "phoneSource": "https://happyhouseexteriors.com/"
  },
  {
    "id": 1054,
    "industry": "Mobile RV repair",
    "priority": 54,
    "business": "Reynolds Mobile RV Service",
    "cityArea": "Marengo, IA",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 193 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://reynoldsmobile.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(319) 936-1889",
    "phoneSource": "https://reynoldsmobile.com/"
  },
  {
    "id": 1055,
    "industry": "Cleaning services",
    "priority": 55,
    "business": "Wild Prairie Cleaning",
    "cityArea": "Northeast Kansas",
    "confidence": "High",
    "reviewSignal": "5 rating · 14 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://wildprairiecleaning.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(785) 370-3504",
    "phoneSource": "https://wildprairiecleaning.com/"
  },
  {
    "id": 1056,
    "industry": "Exterior cleaning",
    "priority": 56,
    "business": "EverGlow Exteriors",
    "cityArea": "Urbandale, IA",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://everglowexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(515) 642-1986",
    "phoneSource": "https://everglowexteriors.com/"
  },
  {
    "id": 1057,
    "industry": "Pressure washing",
    "priority": 57,
    "business": "Prairie Power Wash",
    "cityArea": "Orland Park, IL",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://chicago.craigslist.org/sox/lbs/d/orland-park-power-washresidential/7922703396.html",
    "verifiedDate": "2026-08-31",
    "phone": "(708) 620-7686",
    "phoneSource": "https://chicago.craigslist.org/sox/lbs/d/orland-park-power-washresidential/7922703396.html"
  },
  {
    "id": 1058,
    "industry": "Cleaning and janitorial",
    "priority": 58,
    "business": "Done Just Right",
    "cityArea": "Roselle, IL",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.djrcleaning.com/contact-us",
    "verifiedDate": "2026-08-31",
    "phone": "(630) 893-0757",
    "phoneSource": "https://www.djrcleaning.com/contact-us"
  },
  {
    "id": 1059,
    "industry": "Mobile auto detailing",
    "priority": 59,
    "business": "Fine Finish Mobile Detail",
    "cityArea": "Olathe, KS",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.finefinishmobiledetail.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(913) 388-0206",
    "phoneSource": "https://www.finefinishmobiledetail.com/"
  },
  {
    "id": 1060,
    "industry": "Roofing and restoration",
    "priority": 60,
    "business": "Horizon Restoration",
    "cityArea": "Chicago, IL",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 293 reviews · Established / check vendor · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Can likely afford service; qualify whether review automation already exists",
    "prospectSource": "https://horizonrestoration.com/roofing-contractor-in-chicago-horizon-restoration/contact-us/",
    "verifiedDate": "2026-08-31",
    "phone": "(773) 993-0998",
    "phoneSource": "https://horizonrestoration.com/roofing-contractor-in-chicago-horizon-restoration/contact-us/"
  }
] satisfies Prospect[];
