import type { Prospect } from "./prospects";

export const replacementProspects = [
  {
    "id": 1001,
    "industry": "Mobile notary",
    "priority": 1,
    "business": "Signed On Time Mobile Notary",
    "cityArea": "Waynesville, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.signedontime.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 226-9052",
    "phoneSource": "https://www.signedontime.com/contact"
  },
  {
    "id": 1002,
    "industry": "Remodeling",
    "priority": 2,
    "business": "Fullard Quality Renovations",
    "cityArea": "Toledo, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.bladehomes.com/wp-content/uploads/2025/08/RET-08212025.pdf",
    "verifiedDate": "2026-08-31",
    "phone": "(567) 395-8149",
    "phoneSource": "https://www.bladehomes.com/wp-content/uploads/2025/08/RET-08212025.pdf"
  },
  {
    "id": 1003,
    "industry": "IT services",
    "priority": 3,
    "business": "CORCENT",
    "cityArea": "Gahanna, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.corcent.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 289-8000",
    "phoneSource": "https://www.corcent.com/"
  },
  {
    "id": 1004,
    "industry": "Marketing agency",
    "priority": 4,
    "business": "Upward Digital Marketing Group",
    "cityArea": "Westerville, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.upwarddigitalmarketing.com/contact/",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 699-3010",
    "phoneSource": "https://www.upwarddigitalmarketing.com/contact/"
  },
  {
    "id": 1005,
    "industry": "Remodeling",
    "priority": 5,
    "business": "Ohio Home Doctor",
    "cityArea": "Dayton, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.trustindex.io/reviews/www.ohiohomedoctorremodeling.com",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 605-6882",
    "phoneSource": "https://www.trustindex.io/reviews/www.ohiohomedoctorremodeling.com"
  },
  {
    "id": 1006,
    "industry": "Remodeling",
    "priority": 6,
    "business": "Elite Building & Remodeling",
    "cityArea": "Madison, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.elitebuildbright.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(440) 417-6930",
    "phoneSource": "https://www.elitebuildbright.com/"
  },
  {
    "id": 1007,
    "industry": "Marketing agency",
    "priority": 7,
    "business": "Adept Creative",
    "cityArea": "Cleveland, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://adeptcreative.com/contact/",
    "verifiedDate": "2026-08-31",
    "phone": "(216) 452-6559",
    "phoneSource": "https://adeptcreative.com/contact/"
  },
  {
    "id": 1008,
    "industry": "Accounting and tax",
    "priority": 8,
    "business": "CP & A Tax Services Company",
    "cityArea": "Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.cpataxservicescompany.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 512-4777",
    "phoneSource": "https://www.cpataxservicescompany.com/"
  },
  {
    "id": 1009,
    "industry": "Med spa and aesthetics",
    "priority": 9,
    "business": "Handcrafted Aesthetics & Medical Spa",
    "cityArea": "Gahanna, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Appointment completion creates a repeatable, privacy-sensitive review request trigger.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.handcraftedaesthetics.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(614) 999-0384",
    "phoneSource": "https://www.handcraftedaesthetics.com/contact"
  },
  {
    "id": 1010,
    "industry": "Home improvement",
    "priority": 10,
    "business": "Energy Plus Home Improvements",
    "cityArea": "Alma, MI",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://energyplushomeimprovements.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(989) 833-1000",
    "phoneSource": "https://energyplushomeimprovements.com/"
  },
  {
    "id": 1011,
    "industry": "Landscaping",
    "priority": 11,
    "business": "Blackstone Landscaping",
    "cityArea": "Southeast Michigan",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 32 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.blackstonelandscaping.com/leading-landscaping-contractor-blackstone-se-michigan/",
    "verifiedDate": "2026-08-31",
    "phone": "(248) 939-3600",
    "phoneSource": "https://www.blackstonelandscaping.com/leading-landscaping-contractor-blackstone-se-michigan/"
  },
  {
    "id": 1012,
    "industry": "HVAC",
    "priority": 12,
    "business": "Wiegand & Sons HVAC",
    "cityArea": "Muskegon, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://wiegandandsonshvac.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 566-0921",
    "phoneSource": "https://wiegandandsonshvac.com/"
  },
  {
    "id": 1013,
    "industry": "Home builder",
    "priority": 13,
    "business": "All American Home Builders",
    "cityArea": "Grass Lake, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.allamericanhomebuilders.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(517) 206-3175",
    "phoneSource": "https://www.allamericanhomebuilders.com/"
  },
  {
    "id": 1014,
    "industry": "Roofing and restoration",
    "priority": 14,
    "business": "Saia & Sons Restoration",
    "cityArea": "Crown Point, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.saiarestoration.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(219) 209-2433",
    "phoneSource": "https://www.saiarestoration.com/"
  },
  {
    "id": 1015,
    "industry": "Electrical",
    "priority": 15,
    "business": "Sumnicht Electric",
    "cityArea": "Neenah, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 50 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://sumnichtelectric.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(920) 268-2509",
    "phoneSource": "https://sumnichtelectric.com/"
  },
  {
    "id": 1016,
    "industry": "Real estate",
    "priority": 16,
    "business": "Rennie Barton Team",
    "cityArea": "Grandville, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 37 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://renniebartonluxury.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 856-1492",
    "phoneSource": "https://renniebartonluxury.com/"
  },
  {
    "id": 1017,
    "industry": "Electrical",
    "priority": 17,
    "business": "Elite Electrical Solutions",
    "cityArea": "Lawrenceburg, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 130 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.eliteelectrical.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 502-4780",
    "phoneSource": "https://www.eliteelectrical.com/contact"
  },
  {
    "id": 1018,
    "industry": "Plumbing",
    "priority": 18,
    "business": "Dearborn Plumbing",
    "cityArea": "Dearborn, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://dearbornsplumber.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(313) 614-6818",
    "phoneSource": "https://dearbornsplumber.com/"
  },
  {
    "id": 1019,
    "industry": "Electrical",
    "priority": 19,
    "business": "JCH Electric",
    "cityArea": "White Cloud, MI",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.jchelectric.net/",
    "verifiedDate": "2026-08-31",
    "phone": "(231) 250-2099",
    "phoneSource": "https://www.jchelectric.net/"
  },
  {
    "id": 1020,
    "industry": "Roofing and remodeling",
    "priority": 20,
    "business": "Kohlfeld Contracting",
    "cityArea": "Mehlville, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 15 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.kohlfeldcontracting.com/about-us",
    "verifiedDate": "2026-08-31",
    "phone": "(314) 329-1873",
    "phoneSource": "https://www.kohlfeldcontracting.com/about-us"
  },
  {
    "id": 1021,
    "industry": "Landscaping",
    "priority": 21,
    "business": "Soriano's Landscaping",
    "cityArea": "Kansas City, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 24 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://sorianoslandscaping.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(816) 874-9554",
    "phoneSource": "https://sorianoslandscaping.com/"
  },
  {
    "id": 1022,
    "industry": "Trenchless plumbing",
    "priority": 22,
    "business": "Gustum Trenchless Repair",
    "cityArea": "Sand Creek, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 10 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://gustumtrenchless.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(715) 658-6070",
    "phoneSource": "https://gustumtrenchless.com/"
  },
  {
    "id": 1023,
    "industry": "Roofing and siding",
    "priority": 23,
    "business": "New Beginning Exteriors",
    "cityArea": "Saint Paul, MN",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.newbeginningexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 741-5569",
    "phoneSource": "https://www.newbeginningexteriors.com/"
  },
  {
    "id": 1024,
    "industry": "Remodeling",
    "priority": 24,
    "business": "Dawson Contracting",
    "cityArea": "Marshall, MO",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://dawsoncontracting.com/index.html",
    "verifiedDate": "2026-08-31",
    "phone": "(660) 886-8521",
    "phoneSource": "https://dawsoncontracting.com/index.html"
  },
  {
    "id": 1025,
    "industry": "Roofing and siding",
    "priority": 25,
    "business": "Advanced Roofing & Siding",
    "cityArea": "Oak Grove, MN",
    "confidence": "High",
    "reviewSignal": "5 rating · 175 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.advancedroofingmn.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(763) 427-3039",
    "phoneSource": "https://www.advancedroofingmn.com/"
  },
  {
    "id": 1026,
    "industry": "Mobile diesel repair",
    "priority": 26,
    "business": "Mudhollow Mobile Diesel Mechanics",
    "cityArea": "Western Iowa",
    "confidence": "High",
    "reviewSignal": "5 rating · 58 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://mudhollowdieselmechanics.com/testimonials/",
    "verifiedDate": "2026-08-31",
    "phone": "(712) 827-0207",
    "phoneSource": "https://mudhollowdieselmechanics.com/testimonials/"
  },
  {
    "id": 1027,
    "industry": "Roofing and remodeling",
    "priority": 27,
    "business": "Innovative Building & Design",
    "cityArea": "Blaine, MN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://innovativebuilding.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 808-6025",
    "phoneSource": "https://innovativebuilding.com/"
  },
  {
    "id": 1028,
    "industry": "Plumbing",
    "priority": 28,
    "business": "Posey Family Plumbing",
    "cityArea": "Washington, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 127 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.poseyfamilyplumbing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(314) 620-4809",
    "phoneSource": "https://www.poseyfamilyplumbing.com/"
  },
  {
    "id": 1029,
    "industry": "Plumbing and electrical",
    "priority": 29,
    "business": "Midway Electric",
    "cityArea": "Columbia, MO",
    "confidence": "High",
    "reviewSignal": "4.8 rating · Verify count · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.midwayelectricinc.com/plumbing/",
    "verifiedDate": "2026-08-31",
    "phone": "(573) 446-2484",
    "phoneSource": "https://www.midwayelectricinc.com/plumbing/"
  },
  {
    "id": 1030,
    "industry": "Tree service",
    "priority": 30,
    "business": "The Industry Standard Tree Service",
    "cityArea": "Fort Wayne, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 31 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://tistrees.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(260) 298-1652",
    "phoneSource": "https://tistrees.com/"
  },
  {
    "id": 1031,
    "industry": "Carpet cleaning",
    "priority": 31,
    "business": "Meyer Carpet Cleaning",
    "cityArea": "West Bend, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 91 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.meyercarpetcleaning.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(414) 610-9507",
    "phoneSource": "https://www.meyercarpetcleaning.com/"
  },
  {
    "id": 1032,
    "industry": "Pressure washing",
    "priority": 32,
    "business": "Redhead Pressure Cleaning",
    "cityArea": "Springboro, OH",
    "confidence": "High",
    "reviewSignal": "5 rating · 55 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://redheadpressurecleaning.com/reviews",
    "verifiedDate": "2026-08-31",
    "phone": "(351) 242-0666",
    "phoneSource": "https://redheadpressurecleaning.com/reviews"
  },
  {
    "id": 1033,
    "industry": "Dumpster rental",
    "priority": 33,
    "business": "J's Dumpster Rentals",
    "cityArea": "Richmond, IN",
    "confidence": "High",
    "reviewSignal": "5 rating · 119 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://richmonddumpstersin.com/contact.html",
    "verifiedDate": "2026-08-31",
    "phone": "(765) 238-1393",
    "phoneSource": "https://richmonddumpstersin.com/contact.html"
  },
  {
    "id": 1034,
    "industry": "Home inspection",
    "priority": 34,
    "business": "Wolf Inspectors",
    "cityArea": "Greater Cincinnati, OH",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.wolfhomeinspector.com/reviews.html",
    "verifiedDate": "2026-08-31",
    "phone": "(513) 720-9100",
    "phoneSource": "https://www.wolfhomeinspector.com/reviews.html"
  },
  {
    "id": 1035,
    "industry": "Mobile auto detailing",
    "priority": 35,
    "business": "444 Mobile Detailing",
    "cityArea": "Wixom, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 6 reviews · Too early / qualify · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Emerging business; verify budget and monthly customer volume",
    "prospectSource": "https://444mobiledetailing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(810) 844-9137",
    "phoneSource": "https://444mobiledetailing.com/"
  },
  {
    "id": 1036,
    "industry": "Exterior cleaning",
    "priority": 36,
    "business": "Elevation Exterior Cleaning",
    "cityArea": "Wyoming, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 49 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://elevationexteriorcleaning.com/commercial-exterior-cleaning-rockford/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 229-0625",
    "phoneSource": "https://elevationexteriorcleaning.com/commercial-exterior-cleaning-rockford/"
  },
  {
    "id": 1037,
    "industry": "Cleaning services",
    "priority": 37,
    "business": "Watkins Cleaning Company",
    "cityArea": "Southeast Michigan",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.michiganfcs.com/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(248) 225-5027",
    "phoneSource": "https://www.michiganfcs.com/contact"
  },
  {
    "id": 1038,
    "industry": "Mobile auto detailing",
    "priority": 38,
    "business": "CJM Mobile Detailing",
    "cityArea": "Byron Center, MI",
    "confidence": "High",
    "reviewSignal": "5 rating · 49 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://cjmautodetailing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(616) 801-4439",
    "phoneSource": "https://cjmautodetailing.com/"
  },
  {
    "id": 1039,
    "industry": "Auto audio tint detailing",
    "priority": 39,
    "business": "Rewired Mobile Solutions",
    "cityArea": "Racine, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://rewiredmobilesolutions.org/",
    "verifiedDate": "2026-08-31",
    "phone": "(262) 554-1202",
    "phoneSource": "https://rewiredmobilesolutions.org/"
  },
  {
    "id": 1040,
    "industry": "Carpet cleaning",
    "priority": 40,
    "business": "Hi Tek Professional Carpet Care",
    "cityArea": "Lake Geneva, WI",
    "confidence": "High",
    "reviewSignal": "5 rating · 100 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.hitekprofessionalcarpetcare.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(262) 995-5085",
    "phoneSource": "https://www.hitekprofessionalcarpetcare.com/"
  },
  {
    "id": 1041,
    "industry": "Pressure washing",
    "priority": 41,
    "business": "Fishers Power Washing",
    "cityArea": "Fishers, IN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 45 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://www.fisherspowerwashing.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(317) 572-7061",
    "phoneSource": "https://www.fisherspowerwashing.com/"
  },
  {
    "id": 1042,
    "industry": "House cleaning",
    "priority": 42,
    "business": "Xtra Mile Cleaning",
    "cityArea": "Bay County, MI",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 14 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://extra-mile-cleaning.lovable.app/",
    "verifiedDate": "2026-08-31",
    "phone": "(810) 336-4890",
    "phoneSource": "https://extra-mile-cleaning.lovable.app/"
  },
  {
    "id": 1043,
    "industry": "Home technology",
    "priority": 43,
    "business": "Simplified Tech",
    "cityArea": "Minnesota",
    "confidence": "High",
    "reviewSignal": "5 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.simplifiedtech.io/contact",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 567-8567",
    "phoneSource": "https://www.simplifiedtech.io/contact"
  },
  {
    "id": 1044,
    "industry": "Auto repair",
    "priority": 44,
    "business": "DAVID's Auto Care",
    "cityArea": "Sioux Falls, SD",
    "confidence": "High",
    "reviewSignal": "4.8 rating · 84 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://davidsautocare.com/reviews/",
    "verifiedDate": "2026-08-31",
    "phone": "(605) 929-7027",
    "phoneSource": "https://davidsautocare.com/reviews/"
  },
  {
    "id": 1045,
    "industry": "Auto detailing",
    "priority": 45,
    "business": "MC Auto Detailing",
    "cityArea": "Lincoln, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 80 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://mcautodetailinglincoln.com/reviews",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 525-7201",
    "phoneSource": "https://mcautodetailinglincoln.com/reviews"
  },
  {
    "id": 1046,
    "industry": "Junk removal",
    "priority": 46,
    "business": "Fuzed Enterprises",
    "cityArea": "Omaha, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 80 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://fuzedenterprises.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 709-1531",
    "phoneSource": "https://fuzedenterprises.com/"
  },
  {
    "id": 1047,
    "industry": "Self storage",
    "priority": 47,
    "business": "Superior Storage",
    "cityArea": "St. Michael, MN",
    "confidence": "High",
    "reviewSignal": "4 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.selfstorage-us.com/about",
    "verifiedDate": "2026-08-31",
    "phone": "(763) 200-6443",
    "phoneSource": "https://www.selfstorage-us.com/about"
  },
  {
    "id": 1048,
    "industry": "Custom home builder",
    "priority": 48,
    "business": "Choice Custom Homes",
    "cityArea": "Elkhorn, NE",
    "confidence": "High",
    "reviewSignal": "5 rating · 54 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://choicecustomhomesne.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 850-1186",
    "phoneSource": "https://choicecustomhomesne.com/"
  },
  {
    "id": 1049,
    "industry": "Roofing and exteriors",
    "priority": 49,
    "business": "Statement Exteriors",
    "cityArea": "Omaha, NE",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 200 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://statementext.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(402) 915-4245",
    "phoneSource": "https://statementext.com/"
  },
  {
    "id": 1050,
    "industry": "Real estate",
    "priority": 50,
    "business": "Dan Salamone Realtor",
    "cityArea": "New Hope, MN",
    "confidence": "High",
    "reviewSignal": "5 rating · 15 reviews · Ideal band · publicly invites texts",
    "fitReason": "High-value local decisions are strongly influenced by recent social proof.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://dansalamonerealtor.com/2026/02/01/read-this-before-you-sell-to-homestead-road/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 404-9708",
    "phoneSource": "https://dansalamonerealtor.com/2026/02/01/read-this-before-you-sell-to-homestead-road/"
  },
  {
    "id": 1051,
    "industry": "Exterior cleaning",
    "priority": 51,
    "business": "Vitality Pro Wash",
    "cityArea": "Bloomington, MN",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 121 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://vitalityprowash.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 644-8870",
    "phoneSource": "https://vitalityprowash.com/"
  },
  {
    "id": 1052,
    "industry": "Home inspection",
    "priority": 52,
    "business": "Comfort Home Inspections",
    "cityArea": "Minnesota",
    "confidence": "High",
    "reviewSignal": "4.9 rating · Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.comforthomeinspections.net/",
    "verifiedDate": "2026-08-31",
    "phone": "(612) 469-9707",
    "phoneSource": "https://www.comforthomeinspections.net/"
  },
  {
    "id": 1053,
    "industry": "Exterior cleaning",
    "priority": 53,
    "business": "Happy House Exteriors",
    "cityArea": "Springfield, MO",
    "confidence": "High",
    "reviewSignal": "5 rating · 160 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://happyhouseexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(417) 766-8666",
    "phoneSource": "https://happyhouseexteriors.com/"
  },
  {
    "id": 1054,
    "industry": "Mobile RV repair",
    "priority": 54,
    "business": "Reynolds Mobile RV Service",
    "cityArea": "Marengo, IA",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 193 reviews · Ideal band · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://reynoldsmobile.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(319) 936-1889",
    "phoneSource": "https://reynoldsmobile.com/"
  },
  {
    "id": 1055,
    "industry": "Cleaning services",
    "priority": 55,
    "business": "Wild Prairie Cleaning",
    "cityArea": "Northeast Kansas",
    "confidence": "High",
    "reviewSignal": "5 rating · 14 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://wildprairiecleaning.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(785) 370-3504",
    "phoneSource": "https://wildprairiecleaning.com/"
  },
  {
    "id": 1056,
    "industry": "Exterior cleaning",
    "priority": 56,
    "business": "EverGlow Exteriors",
    "cityArea": "Urbandale, IA",
    "confidence": "High",
    "reviewSignal": "5 rating · 19 reviews · Ideal band · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Strong target band: enough proof of demand, still meaningful review headroom",
    "prospectSource": "https://everglowexteriors.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(515) 642-1986",
    "phoneSource": "https://everglowexteriors.com/"
  },
  {
    "id": 1057,
    "industry": "Pressure washing",
    "priority": 57,
    "business": "Prairie Power Wash",
    "cityArea": "Orland Park, IL",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://chicago.craigslist.org/sox/lbs/d/orland-park-power-washresidential/7922703396.html",
    "verifiedDate": "2026-08-31",
    "phone": "(708) 620-7686",
    "phoneSource": "https://chicago.craigslist.org/sox/lbs/d/orland-park-power-washresidential/7922703396.html"
  },
  {
    "id": 1058,
    "industry": "Cleaning and janitorial",
    "priority": 58,
    "business": "Done Just Right",
    "cityArea": "Roselle, IL",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.djrcleaning.com/contact-us",
    "verifiedDate": "2026-08-31",
    "phone": "(630) 893-0757",
    "phoneSource": "https://www.djrcleaning.com/contact-us"
  },
  {
    "id": 1059,
    "industry": "Mobile auto detailing",
    "priority": 59,
    "business": "Fine Finish Mobile Detail",
    "cityArea": "Olathe, KS",
    "confidence": "High",
    "reviewSignal": "Verify count · publicly invites texts",
    "fitReason": "Repeatable customer-completion moments and local search visibility make reviews commercially valuable.",
    "qualificationNote": "Publicly advertised for texts. Verify current Google/Facebook review count before outreach",
    "prospectSource": "https://www.finefinishmobiledetail.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(913) 388-0206",
    "phoneSource": "https://www.finefinishmobiledetail.com/"
  },
  {
    "id": 1060,
    "industry": "Roofing and restoration",
    "priority": 60,
    "business": "Horizon Restoration",
    "cityArea": "Chicago, IL",
    "confidence": "High",
    "reviewSignal": "4.9 rating · 293 reviews · Established / check vendor · publicly invites texts",
    "fitReason": "Completed jobs create a clear automation trigger and each new lead can be high value.",
    "qualificationNote": "Publicly advertised for texts. Can likely afford service; qualify whether review automation already exists",
    "prospectSource": "https://horizonrestoration.com/roofing-contractor-in-chicago-horizon-restoration/contact-us/",
    "verifiedDate": "2026-08-31",
    "phone": "(773) 993-0998",
    "phoneSource": "https://horizonrestoration.com/roofing-contractor-in-chicago-horizon-restoration/contact-us/"
  },
  {
    "id": 1061,
    "industry": "Auto repair",
    "priority": 61,
    "business": "Gateway Auto Clinic",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Independent repair shop with clear repair-order completion trigger",
    "qualificationNote": "Texting unconfirmed. Confirm owner and current review count",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1v2srxk/need_an_honest_mechanic_in_dayton_please/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 435-8094",
    "phoneSource": "https://www.gatewayautoclinic.com/contact-us"
  },
  {
    "id": 1062,
    "industry": "Auto repair",
    "priority": 62,
    "business": "Grace Tire & Auto Service",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Family-run shop and accessible decision maker",
    "qualificationNote": "Texting unconfirmed. Confirm owner and shop-management software",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1v2srxk/need_an_honest_mechanic_in_dayton_please/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 813-1010",
    "phoneSource": "https://www.chamberofcommerce.com/business-directory/ohio/kettering/auto-repair-shop/2026339397-grace-tire-auto-service"
  },
  {
    "id": 1063,
    "industry": "Auto repair",
    "priority": 63,
    "business": "Murphy's Autocare",
    "cityArea": "Beavercreek, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Independent shop with completed-repair workflow",
    "qualificationNote": "Texting unconfirmed. Confirm current review count",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1jys2tj/independent_car_service_shop_in_beavercreek_area/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 426-2886",
    "phoneSource": "https://murphysautocare.com/contact/"
  },
  {
    "id": 1064,
    "industry": "Auto repair",
    "priority": 64,
    "business": "Centerville Automotive",
    "cityArea": "Centerville, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Established suburban repair shop",
    "qualificationNote": "Texting unconfirmed. Confirm ownership and software",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1urek7k/recommendations_for_an_honest_mechanic/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 435-6460",
    "phoneSource": "https://autoservicecenterville.com/"
  },
  {
    "id": 1065,
    "industry": "Auto repair",
    "priority": 65,
    "business": "Augustine Automotive",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Independent specialist with completed-service trigger",
    "qualificationNote": "Texting unconfirmed. Confirm review velocity before outreach",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1ruv68r/best_and_most_affordable_place_to_have_a_foreign/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 912-0026",
    "phoneSource": "https://www.augustineautomotive.com/"
  },
  {
    "id": 1066,
    "industry": "HVAC",
    "priority": 66,
    "business": "Watkins Heating & Cooling",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · 149 reviews · Ideal band · business phone verified",
    "fitReason": "Strong volume with room below dominant local firms",
    "qualificationNote": "Texting unconfirmed. Confirm independent marketing authority",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/hvac/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 806-5289",
    "phoneSource": "https://www.watkinsheating.com/about/"
  },
  {
    "id": 1067,
    "industry": "HVAC",
    "priority": 67,
    "business": "Seiter Services LLC",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · 136 reviews · Ideal band · business phone verified",
    "fitReason": "Ideal review-count band and service-call trigger",
    "qualificationNote": "Texting unconfirmed. Confirm CRM or dispatch software",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/hvac/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 507-3372",
    "phoneSource": "https://www.seiterservices.com/"
  },
  {
    "id": 1068,
    "industry": "HVAC",
    "priority": 68,
    "business": "Korrect Plumbing Heating & Air Conditioning",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · 246 reviews · Ideal band · business phone verified",
    "fitReason": "High residential job volume and clear completion event",
    "qualificationNote": "Texting unconfirmed. May already use review automation",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/hvac/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 837-2333",
    "phoneSource": "https://korrectplumbing.com/contact-us"
  },
  {
    "id": 1069,
    "industry": "HVAC",
    "priority": 69,
    "business": "Barker Heating and Air Conditioning",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · 531 reviews · Established / check vendor · business phone verified",
    "fitReason": "Established local operator with high job volume",
    "qualificationNote": "Texting unconfirmed. Qualify existing review process first",
    "prospectSource": "https://reviews.birdeye.com/d/heating-air-conditioning-hvac/dayton-oh/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 222-2275",
    "phoneSource": "https://www.barkerhvac.com/"
  },
  {
    "id": 1070,
    "industry": "HVAC",
    "priority": 70,
    "business": "Drake Heating and Air",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · 857 reviews · Established / check vendor · business phone verified",
    "fitReason": "Very strong volume and software maturity",
    "qualificationNote": "Texting unconfirmed. Likely already has a review vendor",
    "prospectSource": "https://reviews.birdeye.com/d/heating-air-conditioning-hvac/dayton-oh/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 472-0640",
    "phoneSource": "https://www.linkedin.com/company/drake-heating-and-air"
  },
  {
    "id": 1071,
    "industry": "Plumbing",
    "priority": 71,
    "business": "Oakwood Plumbing",
    "cityArea": "Oakwood, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Local reputation matters and jobs close cleanly",
    "qualificationNote": "Texting unconfirmed. Confirm review count and software",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1u4sd06/plumber_recommendations_looking_for_someone_i_can/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 985-4077",
    "phoneSource": "https://www.oakwoodplumbingcompany.com/"
  },
  {
    "id": 1072,
    "industry": "Plumbing",
    "priority": 72,
    "business": "Dayton Sewer and Drain",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "High-intent completed jobs and accessible owner",
    "qualificationNote": "Texting unconfirmed. Confirm service volume",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1u4sd06/plumber_recommendations_looking_for_someone_i_can/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 552-5954",
    "phoneSource": "https://daytonplumbingcompany.com/contact/"
  },
  {
    "id": 1073,
    "industry": "Plumbing",
    "priority": 73,
    "business": "Advantage Plumbing & Drain Solutions",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Multiple service lines and clear completion event",
    "qualificationNote": "Texting unconfirmed. Confirm current review velocity",
    "prospectSource": "https://advantageplumbinganddrainsolutions.com/wp-content/uploads/2023/02/Advantage-Plumbing-Drain-Solutions.pdf",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 446-6909",
    "phoneSource": "https://advantageplumbinganddrainsolutions.com/wp-content/uploads/2023/02/Advantage-Plumbing-Drain-Solutions.pdf"
  },
  {
    "id": 1074,
    "industry": "Plumbing",
    "priority": 74,
    "business": "Spartan Plumbing",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Residential service volume supports automation",
    "qualificationNote": "Texting unconfirmed. Confirm local ownership",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/plumbers/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 821-6100",
    "phoneSource": "https://spartanplumbingdayton.com/contact/"
  },
  {
    "id": 1075,
    "industry": "Plumbing",
    "priority": 75,
    "business": "Logan Services",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "2 rating · Verify count · business phone verified",
    "fitReason": "High volume and mature dispatch workflow",
    "qualificationNote": "Texting unconfirmed. May already have automation and centralized marketing",
    "prospectSource": "https://www.logan-inc.com/blog/best-of-dayton-2026-winner/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 224-3200",
    "phoneSource": "https://www.logan-inc.com/contact-us/"
  },
  {
    "id": 1076,
    "industry": "Electrical",
    "priority": 76,
    "business": "Rolo Electric",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · 213 reviews · Ideal band · business phone verified",
    "fitReason": "Ideal mix of volume and review headroom",
    "qualificationNote": "Texting unconfirmed. Confirm dispatch platform",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/electricians/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 479-0617",
    "phoneSource": "https://www.rolo-electric.com/contact-me"
  },
  {
    "id": 1077,
    "industry": "Electrical",
    "priority": 77,
    "business": "Bates Electric",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Residential job completion is a clean trigger",
    "qualificationNote": "Texting unconfirmed. Confirm owner contact",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/electricians/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 410-3938",
    "phoneSource": "https://www.bateselec.com/contact-us/"
  },
  {
    "id": 1078,
    "industry": "Electrical",
    "priority": 78,
    "business": "Sparks Electric Service",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.7 rating · 23 reviews · Ideal band · business phone verified",
    "fitReason": "Established firm with a visible review gap",
    "qualificationNote": "Texting unconfirmed. Confirm residential job volume",
    "prospectSource": "https://www.expertise.com/home-improvement/electricians/ohio/dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 890-7188",
    "phoneSource": "https://www.sparkselectricservice.com/electrician/dayton-oh"
  },
  {
    "id": 1079,
    "industry": "Electrical",
    "priority": 79,
    "business": "Henlee Electric",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · Verify count · business phone verified",
    "fitReason": "Local operator with service-call workflow",
    "qualificationNote": "Texting unconfirmed. Confirm Google review count",
    "prospectSource": "https://threebestrated.com/local-electricians-in-dayton-oh",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 510-6088",
    "phoneSource": "https://www.carrollhs.org/editoruploads/files/2024%20Carroll%20Small%20Business%20Directory.pdf"
  },
  {
    "id": 1080,
    "industry": "Electrical",
    "priority": 80,
    "business": "Wells Electric",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Generator and service work create steady triggers",
    "qualificationNote": "Texting unconfirmed. Confirm independent ownership",
    "prospectSource": "https://www.bestprosintown.com/oh/dayton/electricians/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 274-7351",
    "phoneSource": "https://www.bbb.org/us/oh/dayton/profile/electrician/wells-electric-service-llc-0322-7050"
  },
  {
    "id": 1081,
    "industry": "Dental and orthodontics",
    "priority": 81,
    "business": "Dayton Dental Collaborative",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Multi-provider practice with appointment-completion trigger",
    "qualificationNote": "Texting unconfirmed. Requires privacy-safe integration and BAA review",
    "prospectSource": "https://www.smileddc.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 435-5163",
    "phoneSource": "https://www.smileddc.com/contact-us"
  },
  {
    "id": 1082,
    "industry": "Dental and orthodontics",
    "priority": 82,
    "business": "Brilliant Smiles Riverside",
    "cityArea": "Riverside, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Established multi-service practice and accessible local team",
    "qualificationNote": "Texting unconfirmed. Requires privacy-safe integration and BAA review",
    "prospectSource": "https://www.brilliantsmilesriverside.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 252-1463",
    "phoneSource": "https://www.brilliantsmilesriverside.com/"
  },
  {
    "id": 1083,
    "industry": "Dental and orthodontics",
    "priority": 83,
    "business": "Keep Smiling Dental",
    "cityArea": "Beavercreek, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Appointment volume and strong local reputation",
    "qualificationNote": "Texting unconfirmed. Confirm location-level buying authority",
    "prospectSource": "https://roddydental.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 426-5340",
    "phoneSource": "https://roddydental.com/contact-us/"
  },
  {
    "id": 1084,
    "industry": "Dental and orthodontics",
    "priority": 84,
    "business": "Dayton Comprehensive Dentistry",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Independent practice with patient-completion workflow",
    "qualificationNote": "Texting unconfirmed. Verify official site and BAA requirements",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1766pff/looking_for_a_dentist/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 350-5379",
    "phoneSource": "https://dayton-dentistry.com/"
  },
  {
    "id": 1085,
    "industry": "Dental and orthodontics",
    "priority": 85,
    "business": "Dayton Dental Solutions",
    "cityArea": "Englewood, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Suburban practice with review-driven acquisition",
    "qualificationNote": "Texting unconfirmed. Verify owner and practice software",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1ebf96u/dentist/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 898-8980",
    "phoneSource": "https://www.daytondentalsolutions.com/locations"
  },
  {
    "id": 1086,
    "industry": "Veterinary",
    "priority": 86,
    "business": "Suburban Veterinary Clinic",
    "cityArea": "Centerville, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Independent practice with appointment volume",
    "qualificationNote": "Texting unconfirmed. Confirm integration path and client consent",
    "prospectSource": "https://www.daytonvets.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 433-2160",
    "phoneSource": "https://suburbanvetclinic.com/contact/"
  },
  {
    "id": 1087,
    "industry": "Veterinary",
    "priority": 87,
    "business": "North Main Animal Clinic",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Clear appointment-completion trigger",
    "qualificationNote": "Texting unconfirmed. Confirm practice-management system",
    "prospectSource": "https://www.daytonvets.com/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 890-4744",
    "phoneSource": "https://nmcvet.com/contact/"
  },
  {
    "id": 1088,
    "industry": "Veterinary",
    "priority": 88,
    "business": "Oakwood Veterinary Clinic",
    "cityArea": "Oakwood, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Established neighborhood clinic with accessible owner",
    "qualificationNote": "Texting unconfirmed. Confirm current review velocity",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1pp7upn/vet_recommendations_around_belmont_oakwood_or/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 293-2838",
    "phoneSource": "https://www.oakwood100.com/categorylocal/Pets/3"
  },
  {
    "id": 1089,
    "industry": "Veterinary",
    "priority": 89,
    "business": "Apple Valley Animal Hospital",
    "cityArea": "Beavercreek, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Appointment volume and strong owner trust",
    "qualificationNote": "Texting unconfirmed. Confirm review count and software",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1c1gywb/looking_for_a_good_vet_thats_affordable_inaround/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 426-6950",
    "phoneSource": "https://www.applevalleyah.com/"
  },
  {
    "id": 1090,
    "industry": "Veterinary",
    "priority": 90,
    "business": "Far Hills Veterinary Clinic",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Established practice with review-sensitive local demand",
    "qualificationNote": "Texting unconfirmed. Confirm decision maker",
    "prospectSource": "https://www.reddit.com/r/dayton/comments/1c1gywb/looking_for_a_good_vet_thats_affordable_inaround/",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 434-8224",
    "phoneSource": "https://www.loc8nearme.com/ohio/centerville/far-hills-animal-clinic/4826365/"
  },
  {
    "id": 1091,
    "industry": "Med spa and aesthetics",
    "priority": 91,
    "business": "Spa Medicca",
    "cityArea": "Centerville, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · Verify count · business phone verified",
    "fitReason": "High-ticket appointments and clear completion trigger",
    "qualificationNote": "Texting unconfirmed. Use minimum necessary data and confirm consent",
    "prospectSource": "https://www.buoyhealth.com/providers/Medical%20Spa/OH/Dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 312-9212",
    "phoneSource": "https://spamediccaoh.com/locations/"
  },
  {
    "id": 1092,
    "industry": "Med spa and aesthetics",
    "priority": 92,
    "business": "Premier Medspa",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · Verify count · business phone verified",
    "fitReason": "Local practice with review-driven patient acquisition",
    "qualificationNote": "Texting unconfirmed. Confirm provider count and software",
    "prospectSource": "https://www.buoyhealth.com/providers/Medical%20Spa/OH/Dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 818-1645",
    "phoneSource": "https://www.bbb.org/us/oh/dayton/profile/medical-spa/premier-medspa-0322-1440107040"
  },
  {
    "id": 1093,
    "industry": "Med spa and aesthetics",
    "priority": 93,
    "business": "Wellness Flow Dayton",
    "cityArea": "Oakwood, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · Verify count · business phone verified",
    "fitReason": "Appointment-based services and accessible local operator",
    "qualificationNote": "Texting unconfirmed. Confirm HIPAA exposure and integration",
    "prospectSource": "https://www.buoyhealth.com/providers/Medical%20Spa/OH/Dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 361-7673",
    "phoneSource": "https://uspto.report/TM/98868678/FTK20241122191216/"
  },
  {
    "id": 1094,
    "industry": "Med spa and aesthetics",
    "priority": 94,
    "business": "Quench Aesthetics & Wellness",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.9 rating · Verify count · business phone verified",
    "fitReason": "Local high-margin appointment business",
    "qualificationNote": "Texting unconfirmed. Confirm review count and consent language",
    "prospectSource": "https://www.buoyhealth.com/providers/Medical%20Spa/OH/Dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 901-5685",
    "phoneSource": "https://quenchspa.com/"
  },
  {
    "id": 1095,
    "industry": "Med spa and aesthetics",
    "priority": 95,
    "business": "PureMD MedSpa Dayton",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "4.8 rating · Verify count · business phone verified",
    "fitReason": "Established local location with appointment volume",
    "qualificationNote": "Texting unconfirmed. Confirm local marketing authority",
    "prospectSource": "https://www.buoyhealth.com/providers/Medical%20Spa/OH/Dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(855) 978-7363",
    "phoneSource": "https://www.puremdmedspa.com/locations/"
  },
  {
    "id": 1096,
    "industry": "Property management",
    "priority": 96,
    "business": "Mak Gregor Management",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "5 rating · 222 reviews · Ideal band · business phone verified",
    "fitReason": "Family-run with maintenance and leasing triggers",
    "qualificationNote": "Texting unconfirmed. Request reviews consistently without sentiment gating",
    "prospectSource": "https://www.expertise.com/business/property-management/ohio/dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 898-2661",
    "phoneSource": "https://www.rentmgm.com/owner-info.html"
  },
  {
    "id": 1097,
    "industry": "Property management",
    "priority": 97,
    "business": "EB Real Estate",
    "cityArea": "Greenville, OH",
    "confidence": "Medium",
    "reviewSignal": "4.5 rating · 90 reviews · Ideal band · business phone verified",
    "fitReason": "Ideal review-count range and active maintenance workflow",
    "qualificationNote": "Texting unconfirmed. Near outer radius; verify exact office distance",
    "prospectSource": "https://www.expertise.com/business/property-management/ohio/dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 548-4663",
    "phoneSource": "https://www.zillow.com/profile/EB-Real-Estate"
  },
  {
    "id": 1098,
    "industry": "Property management",
    "priority": 98,
    "business": "Leis Realty",
    "cityArea": "Greenville, OH",
    "confidence": "Medium",
    "reviewSignal": "4.2 rating · 145 reviews · Ideal band · business phone verified",
    "fitReason": "High transaction volume with reputation upside",
    "qualificationNote": "Texting unconfirmed. Near outer radius and no review gating",
    "prospectSource": "https://www.expertise.com/business/property-management/ohio/dayton",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 548-5750",
    "phoneSource": "https://leisrealty.com/"
  },
  {
    "id": 1099,
    "industry": "Property management",
    "priority": 99,
    "business": "Kittyhawk Realty",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Multi-county property workflow and accessible office",
    "qualificationNote": "Texting unconfirmed. Confirm managed-unit count",
    "prospectSource": "https://www.bbb.org/us/oh/dayton/category/property-management/accredited",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 236-5447",
    "phoneSource": "https://www.kittyhawkrealtyinc.com/contact"
  },
  {
    "id": 1100,
    "industry": "Property management",
    "priority": 100,
    "business": "Irongate Property Management",
    "cityArea": "Dayton, OH",
    "confidence": "Medium",
    "reviewSignal": "Verify count · business phone verified",
    "fitReason": "Local decision maker and tenant lifecycle triggers",
    "qualificationNote": "Texting unconfirmed. Confirm exact service offering and review count",
    "prospectSource": "https://www.biggerpockets.com/oh/dayton/property-managers",
    "verifiedDate": "2026-08-31",
    "phone": "(937) 436-3728",
    "phoneSource": "https://www.irongaterealtors.com/property-management.html"
  }
] satisfies Prospect[];
